import React, { createContext, useContext, useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'

export type Lang = 'en' | 'th'

const en = {
  nav: {
    dashboard: 'Dashboard', cases: 'Cases', newCase: 'New Case',
    calendar: 'Calendar', performance: 'Performance',
    maintenance: 'Preventive Maintenance',
    routineRoster: 'Routine Roster',
    notifications: 'Notifications', users: 'Users', settings: 'Settings',
    signOut: 'Sign Out', home: 'Home', alerts: 'Alerts',
  },
  login: {
    title: 'Sign In', signInAs: 'Sign in as', superAdmin: 'Super Admin',
    manager: 'Manager', staff: 'Staff', department: 'Department',
    selectDept: 'Select your department', username: 'Username',
    email: 'Email Address', password: 'Password',
    enterUsername: 'Enter your username', enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    footer: 'Kaizen System · Internal Use Only',
    noDeptError: 'Please select your department.',
    companyCode: 'Company Code',
    enterCompanyCode: 'Your company code',
    noCompanyCode: 'Please enter your company code.',
    forgotPassword: 'Forgot password?',
    backToLogin: 'Back to Sign In',
    resetTitle: 'Reset Password',
    resetSubtitle: 'Enter your email and we\'ll send you a reset link.',
    sendResetLink: 'Send Reset Link',
    resetSent: 'Check your email for a password reset link.',
    contactManager: 'Contact your manager or HR to reset your password.',
    emailNotRegistered: "We couldn't find an account with this email. Please reach out to your system admin or HR department.",
  },
  dashboard: {
    title: 'Dashboard', welcome: 'Welcome back',
    totalCases: 'Total Cases', open: 'Open', inProgress: 'In Progress',
    resolved: 'Resolved', waitingApproval: 'Waiting Approval',
    caseOverview: 'Case Overview', casesShort: 'Cases', totalShort: 'Total',
    monthlyCases: 'Monthly Cases',
    criticalBanner: (n: number) => `${n} critical ${n === 1 ? 'case requires' : 'cases require'} immediate attention.`,
    slaBanner: (n: number) => `${n} case${n === 1 ? '' : 's'} overdue.`,
    view: 'View', recentCases: 'Recent Cases', viewAll: 'View all',
    noCases: 'No cases yet', casesByDept: 'Cases by Department',
    noData: 'No data', newCase: 'New Case',
    avgResolution: 'Avg Resolution', resolutionRate: 'Resolution Rate',
    casesThisMonth: 'Cases This Month', overdueSLA: 'Overdue',
    recurringIssues: 'Recurring Issues',
    deptPerformance: 'Department Performance',
    openCases: 'Open Cases', avgDays: 'Avg Days', overdue: 'Overdue',
    casesByCategory: 'Cases by Category',
  },
  cases: {
    title: 'Cases', newCase: 'New Case',
    search: 'Search by keyword, serial no, case number...', allStatuses: 'All Statuses',
    allPriorities: 'All Priorities', noFound: 'No cases found',
    adjustFilters: 'Try adjusting your filters or create a new case',
    caseNo: 'Case #', titleCol: 'Title', dept: 'Department',
    priority: 'Priority', status: 'Status', age: 'Age', duration: 'Duration',
    export: 'Export', due: 'Due',
    caseCount: (n: number) => `${n} ${n === 1 ? 'case' : 'cases'}`,
    allCategories: 'All Categories', slaBreached: 'Overdue',
    category: 'Category',
  },
  createCase: {
    title: 'Report a Problem', subtitle: 'Document the issue so it can be tracked and resolved',
    caseDetails: 'Case Details', department: 'Department',
    problemTitle: 'Problem Title', problemPlaceholder: 'e.g. Broken chair in dining area, Table 5',
    description: 'Description', descPlaceholder: 'Describe the problem in detail. Include location, severity, and any relevant context...',
    priority: 'Priority', photoEvidence: 'Photo Evidence',
    photoSubtitle: 'Upload photos of the problem to help the team understand the issue.',
    submit: 'Submit Case', cancel: 'Cancel',
    fillRequired: 'Please fill in all required fields.',
    created: (n: string) => `Case ${n} created successfully!`,
    failed: 'Failed to create case. Please try again.',
    dueDate: 'Due Date', optional: '(optional)', addPhotos: 'Add Photos',
    category: 'Category', selectCategory: 'Select category',
    recurring: 'Recurring Problem', recurringHint: 'Check if this issue has happened before',
  },
  status: {
    open: 'Open', assigned: 'Assigned', in_progress: 'In Progress',
    pending_manager_approval: 'Pending Approval',
    pending_admin_approval: 'Pending Approval',
    closed: 'Closed', reopened: 'Reopened',
  },
  priority: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
  users: {
    title: 'Users', addUser: 'Add User', accounts: 'accounts',
    superAdmins: 'Super Admins', managers: 'Managers', staff: 'Staff',
    createTitle: 'Create New User', createSubtitle: 'Add a new staff, manager, or admin account.',
    fullName: 'Full Name', fullNamePlaceholder: 'e.g. Somchai Kaewkham',
    username: 'Username', emailAddress: 'Email Address',
    emailPlaceholder: 'e.g. name@nanirand.com', password: 'Password',
    minPassword: 'Min. 6 characters', createAccount: 'Create Account', cancel: 'Cancel',
    inactive: '(Inactive)', noYet: (label: string) => `No ${label.toLowerCase()} yet`,
    confirmDeactivate: (active: boolean) => `Are you sure you want to ${active ? 'deactivate' : 'reactivate'} this account?`,
    confirmDelete: (name: string) => `Permanently delete ${name}'s account? This cannot be undone.`,
    deactivated: 'Account deactivated.', reactivated: 'Account reactivated.', deleted: 'Account deleted.',
    created: 'Account created successfully.', failedCreate: 'Failed to create user.',
    failedStatus: 'Failed to update account status.', failedDelete: 'Failed to delete account.',
    fillRequired: 'Full name and password are required.',
    usernameRequired: 'Username is required for staff accounts.',
    emailRequired: 'Email is required for manager and admin accounts.',
    minPwd: 'Password must be at least 6 characters.',
    dept: 'Department', roleLabel: 'Role',
    editTitle: 'Edit User', editSubtitle: 'Update user details or reset their password.',
    resetPassword: 'Reset Password', keepCurrent: '(leave blank to keep current)',
    saveChanges: 'Save Changes',
  },
  notifications: {
    title: 'Notifications', markAllRead: 'Mark all read',
    noNotifications: 'No notifications', viewAll: 'View all notifications',
    allTab: 'All', unreadTab: 'Unread', allRead: 'All notifications marked as read.',
    empty: "You're all caught up!",
    today: 'Today', yesterday: 'Yesterday', thisWeek: 'This Week', older: 'Older',
  },
  settings: {
    title: 'Settings', theme: 'Color Theme', themeSubtitle: "Customize the app's color scheme",
    presets: 'Special Presets', primaryColor: 'Primary Color', accentColor: 'Accent Color',
    sidebarColor: 'Sidebar Color', applyTheme: 'Apply Theme', applying: 'Applying...',
    themeApplied: 'Theme updated successfully!', failedTheme: 'Failed to update theme.',
    adminOnly: 'Theme settings can only be changed by Super Admin.',
    changePassword: 'Change Password', passwordSubtitle: 'Update your login password',
    currentPassword: 'Current Password', newPassword: 'New Password',
    confirmPassword: 'Confirm New Password', updatePassword: 'Update Password',
    updating: 'Updating...', passwordUpdated: 'Password updated successfully!',
    failedPassword: 'Failed to update password.', mismatch: 'New passwords do not match.',
    accountInfo: 'Account Information', name: 'Name', role: 'Role', dept: 'Department',
    scoringTitle: 'Performance Scoring',
    scoringSubtitle: 'Adjust how much each indicator counts toward the performance score. Weights are relative — they need not add up to 100.',
    scoringStaffGroup: 'Staff score', scoringManagerGroup: 'Manager score',
    scoringIncludePms: 'Include Preventive Maintenance (PMS) in score',
    scoringIncludeRr: 'Include Routine Roster (RR) in score',
    scoringWeightHint: 'Weights are relative; the share shown is each weight over the active total.',
    scoringSave: 'Save scoring', scoringReset: 'Reset to defaults', scoringSaved: 'Performance scoring saved.',
  },
  caseDetail: {
    caseInfo: 'Case Information', createdBy: 'Created by', reportedOn: 'Reported on',
    translate: 'Translate', showOriginal: 'Show original',
    machineTranslation: 'Machine translation', translateFailed: 'Translation unavailable — please try again.',
    recurringChronic: (n: number) => `Chronic Issue · ${n} reports`,
    recurringRecurring: (n: number) => `Recurring Issue · ${n} reports`,
    recurringOnce: (n: number) => `Reported Before · ${n} report`,
    recurringChronicAdvice: 'This same type of issue has been reported 3+ times at this location. Consider a permanent fix or replacement.',
    recurringRecurringAdvice: 'This same type of issue has been reported multiple times at this location. Monitor closely.',
    recurringOnceAdvice: 'This same type of issue was reported once before at this location.',
    recurringFlagged: 'Flagged Recurring',
    recurringFlaggedAdvice: 'The reporter marked this as a recurring problem — it has happened before.',
    openedBy: 'Opened by:', inCharge: 'In Charge:', dueLabel: 'Due:',
    removedFromCompany: 'No longer with the company',
    addDueDate: '+ Add due date', noDueDate: 'No due date', notifyAll: 'Notify all',
    lastUpdated: 'Last updated', duration: 'Duration',
    proposedSolution: 'Proposed Solution', assignedDepts: 'Departments Involved',
    timeline: 'Timeline', problemPhotos: 'Problem Photos', resolutionPhotos: 'Resolution Photos',
    noPhotos: 'No photos',
    assignDepts: 'Assign Departments', proposeSolution: 'Propose Solution',
    solutionPlaceholder: 'Describe the proposed solution...',
    assignBtn: 'Submit',
    resolveCase: 'Resolve Case', resolutionDesc: 'Resolution Description',
    resolutionPlaceholder: 'Describe how the problem was resolved...',
    uploadEvidence: 'Upload Evidence Photos', submitResolution: 'Submit Resolution',
    approveTitle: 'Approve Resolution', approveDesc: 'Approve and notify Top Management for final review and closure.',
    approveBtn: 'Approve Resolution',
    closeTitle: 'Close Case', closeDesc: 'Confirm the resolution is satisfactory and close this case.', closeBtn: 'Close Case',
    reopenTitle: 'Reopen Case', reopenDesc: 'Reopen this case if the issue was not fully resolved.', reopenBtn: 'Reopen Case',
    deleteTitle: 'Delete Case', deleteDesc: 'Permanently delete this case and all associated data.', deleteBtn: 'Delete Case',
    confirmClose: 'Close this case? This marks it as fully resolved.',
    confirmReopen: 'Reopen this case?',
    confirmDelete: 'Permanently delete this case? This cannot be undone.',
    selectDepts: 'Select at least one department.',
    provideSolution: 'Please provide a proposed solution.',
    provideResolution: 'Please provide a resolution description.',
    notFound: 'Case not found.',
    changePriority: 'Change Priority',
    changePriorityBtn: 'Update Priority',
    priorityChanged: (p: string) => `Priority changed to ${p}.`,
    priorityChangedNotif: (n: string, p: string) => `Case ${n} priority has been changed to ${p} by Super Admin.`,
    editCase: 'Edit Case', assignedTo: 'Assigned to:',
    internalNotes: 'Internal Notes', noNotes: 'No notes yet. Add one below.',
    notePlaceholder: 'Add an internal note...',
    mentionHint: 'Type @ to mention and notify a teammate.',
    postNote: 'Post', noteCount: (n: number) => `${n} note${n !== 1 ? 's' : ''}`,
    noActivity: 'No activity yet',
    openFor: 'Open for', dueDateLabel: 'Due date', daysLeftLabel: 'Days left',
    notSet: 'Not set', dueToday: 'Due Today',
    overdueBy: (n: number) => `Overdue by ${n} day${n !== 1 ? 's' : ''}`,
    daysLeftCount: (n: number) => `${n} day${n !== 1 ? 's' : ''} left`,
    currentPriority: 'Current:',
    editModalTitle: 'Edit Case', fieldTitle: 'Title', fieldDescription: 'Description',
    fieldDueDate: 'Due Date', fieldStatus: 'Status',
    statusManualNote: 'Changing status manually will be recorded in the timeline.',
    saveChanges: 'Save Changes', cancelBtn: 'Cancel',
    assignStaff: 'Assign staff', selectNewPriority: 'Select new priority',
    selectDept: 'Select department', selectStatus: 'Select status',
    noStaffAssigned: 'No staff assigned',
    addDept: 'Add department...', addDeptBtn: 'Add',
    recurringBadge: 'Recurring Issue', printPdf: 'Print / PDF',
    relatedCases: 'Related Cases', linkCase: 'Link a case...', noRelatedCases: 'No related cases',
    unlinkCase: 'Unlink',
  },
  categories: {
    maintenance: 'Maintenance', cleanliness: 'Cleanliness', safety: 'Safety',
    guest_complaint: 'Guest Complaint', equipment: 'Equipment', other: 'Other',
    preventive_maintenance: 'Preventive Maintenance',
  },
  perf: {
    overallTitle: 'Overall Performance Score',
    staffCard: 'Staff scorecard', leadershipCard: 'Leadership scorecard',
    tapHint: 'tap an indicator to see how it’s measured',
    scoreOutOf: 'Score out of 100', weight: 'Weight',
    closed: 'closed', overdue: 'overdue', reopened: 'reopened', avg: 'avg',
    activeDays: 'active days', activeDay: 'active day', actions: 'actions',
    noApprovals: 'no approvals yet', noClosed: 'no closed cases',
    resolutionRate: 'Resolution Rate',
    resolutionRateInfo: 'The share of cases you’re responsible for (reported or In Charge) that you’ve resolved and closed.',
    onTime: 'On-Time Delivery',
    onTimeInfo: 'The share of your cases that are NOT past their due date — how reliably you deliver on time.',
    speed: 'Resolution Speed',
    speedInfo: 'How fast you resolve cases on average, scored against a 48-hour target. Resolving within 48h scores full marks.',
    quality: 'Quality',
    qualityInfo: 'How well your fixes hold up — the share of your resolved cases that did NOT get reopened. Fewer reopens = higher quality.',
    engagement: 'Engagement',
    engagementInfo: 'How actively you engage with Kaizen — your active days over the last 30 days plus in-system actions (updates, comments, resolutions). Measured over a month, so one missed login barely affects it.',
    approval: 'Approval Responsiveness',
    approvalInfo: 'How quickly you approve cases your team submits — the average time from a staff resolution to your approval (target: within 24h). Faster unblocking scores higher.',
    teamRes: 'Team Resolution Rate',
    teamResInfo: 'The share of your department’s cases that have been resolved and closed — your team’s overall output.',
    teamSla: 'Team On-Time Health',
    teamSlaInfo: 'The share of your department’s cases that are NOT overdue — how well you keep the team on schedule.',
    leadership: 'Leadership & Quality',
    leadershipInfo: 'A blend of work quality (few cases reopened) and backlog control (few cases overdue) across your department — how healthy your team’s pipeline is.',
    oversight: 'Oversight Engagement',
    oversightInfo: 'How actively you use Kaizen to manage — your active days over the last 30 days combined with in-system actions (assignments, approvals, comments). A missed day barely moves it; consistent absence lowers it.',
    pmsScore: 'PMS Reliability',
    pmsScoreInfo: 'How dependably preventive-maintenance tasks are completed on time — the share of relevant PM tasks finished by their due date. Higher means equipment upkeep stays on schedule.',
    rrScore: 'Routine Reliability',
    rrScoreInfo: 'How dependably routine roster orders are fulfilled on time — the share of acted-on orders delivered or confirmed by their due time. Higher means daily routine hand-offs stay on schedule.',
  },
  calendar: {
    allDepts: 'All Departments', filterByDept: 'Filter by department',
    today: 'Today', more: 'more', priorityLabel: 'Priority:',
    casesCalendar: 'Cases Calendar',
    combined: 'Combined', casePriority: 'Case Priority:', pmStatus: 'PM Status:',
    routine: 'Routine Roster', rrStatus: 'Routine Status:',
    noMaintenance: 'No maintenance scheduled.', nothingDay: 'Nothing on this day.',
  },
  pm: {
    scheduler: 'Preventive Maintenance Scheduler', open: 'Open',
    addAsset: 'Asset', searchAssets: 'Search asset name/tag, serial no, model name…',
    noAssets: 'No assets registered yet.', noAssetsFiltered: 'No assets match your filter.',
    registerFirst: '+ Register your first asset', next: 'Next',
    good: 'Up to Date', dueSoon: 'Due Soon', overdue: 'Overdue', notScheduled: 'Not Scheduled', inactiveStatus: 'Inactive',
    scheduled: 'Scheduled', inProgress: 'In Progress', awaitingApproval: 'Awaiting Approval', done: 'Done',
    editAsset: 'Edit Asset', registerAsset: 'Register Asset',
    assetName: 'Asset name / tag', assetNamePh: 'e.g. Lobby Split A/C #1',
    equipmentType: 'Equipment type', selectType: '— select —',
    location: 'Location / zone', locationPh: 'Building / floor / room',
    serialNo: 'Serial no.', model: 'Model',
    responsibleDept: 'Responsible department', none: '— none —',
    frequency: 'Frequency', customEvery: 'Custom (every N days)', everyNDays: 'Every N days',
    estMinutes: 'Est. minutes', optional: 'optional',
    lastMaint: 'Last maintenance', nextMaint: 'Next maintenance', purchaseDate: 'Purchase date',
    checklist: 'Maintenance checklist (one item per line)',
    checklistPh: 'Clean / replace filters\nCheck refrigerant\nTest thermostat',
    notesInstr: 'Notes / instructions', activeInclude: 'Active (include in scheduling)',
    save: 'Save', register: 'Register', cancel: 'Cancel', delete: 'Delete',
    assetNameRequired: 'Asset name is required.', assetSaved: 'Asset updated', assetAdded: 'Asset added',
    confirmDeleteAsset: 'Delete this asset? Its maintenance history will be removed.',
    checklistTitle: 'Checklist', pass: 'PASS', fail: 'FAIL', na: 'NA',
    readings: 'Readings', parts: 'Parts', findings: 'Findings', performed: 'Performed',
    readingsLabel: 'Readings / measurements', readingsPh: 'e.g. 12°C, 220V',
    partsLabel: 'Parts / consumables used', findingsLabel: 'Findings / notes',
    start: 'Start', complete: 'Complete', approve: 'Approve', return: 'Return',
    rejectPrompt: 'Reason for returning this task to the technician?',
    recorded: 'Maintenance recorded', approvedToast: 'Maintenance approved', returnedToast: 'Returned to technician',
    awaitingNote: 'Awaiting approval', awaitingBy: 'by the responsible manager / Top Management',
    startFirst: 'Click Start before recording the checklist.',
    readingsPartsRequired: 'Readings / measurements and parts / consumables are required before completing.',
    confirmCompleteTitle: 'Complete this maintenance?',
    confirmCompleteMsg: 'Please confirm the checklist and readings are correct. This action records the maintenance.',
    confirmComplete: 'Yes, complete', confirmCancel: 'Cancel',
    timeline: 'Timeline', tlScheduled: 'Scheduled', tlStarted: 'Started', tlCompleted: 'Completed', tlApproved: 'Approved',
    compliance: 'Compliance', dueThisWeek: 'Due This Week', doneThisMonth: 'Done This Month', onTimeRate: 'On-time rate',
    setupScheduler: 'Set up the scheduler →',
    settingsTitle: 'Preventive Maintenance — Settings',
    settingsDesc: 'Approval, reminder and escalation rules for maintenance tasks.',
    requireApproval: 'Require approval for maintenance tasks',
    requireApprovalDesc: 'When on, a completed task waits for the responsible department manager (or Top Management) to approve before the cycle advances.',
    dueSoonWindow: '"Due soon" window (days)',
    dueSoonWindowDesc: 'Assets turn amber within this many days of their next service.',
    escalateAfter: 'Escalate to a Case after (days overdue)',
    escalateAfterDesc: 'A missed task this many days overdue auto-creates a Case.',
    autoEscalate: 'Auto-escalate overdue maintenance to a Case',
    autoEscalateDesc: "Creates a normal Case (priority High) so an overdue task can't be forgotten.",
    saveSettings: 'Save settings', settingsSaved: 'Maintenance settings saved',
    typesTitle: 'Preventive Maintenance — Equipment Types',
    typesDesc: 'Define the equipment types used when registering maintenance assets. Only Top Management can edit these.',
    newType: 'New type', newTypePh: 'e.g. Heat Pump', category: 'Category', add: 'Add',
    noTypes: 'No equipment types yet.', loadDefaults: 'Load default types',
    on: 'On', off: 'Off', activate: 'Activate', deactivate: 'Deactivate', rename: 'Rename',
    defaultsAdded: 'Default equipment types added', confirmDeleteType: 'Remove equipment type',
  },
  pmReport: {
    button: 'Report',
    title: 'Preventive Maintenance Report',
    subtitle: 'Maintenance health at a glance',
    dateOfReport: 'Date of report',
    period: 'Period', last30: 'Last 30 days', last90: 'Last 90 days', last180: 'Last 180 days', last365: 'Last 12 months',
    printSave: 'Print / Save PDF', close: 'Close',
    vs1m: 'vs 1M', vs3m: 'vs 3M', vs6m: 'vs 6M',
    compliance: 'PM Compliance', onTimeDone: 'On-time done', ofDue: 'of tasks due',
    complianceHelp: 'On-time completed tasks ÷ tasks due in the period.',
    overdue: 'Overdue', overdueTasks: 'overdue tasks', daysOverdue: 'd late', neverPerformed: 'never performed', missedBy: 'missed by',
    noOverdue: 'Nothing overdue — great work.',
    checklistFails: 'Checklist Fails', tasksWithFail: 'tasks with ≥1 failed item', passItems: 'Pass', failItems: 'Fail', naItems: 'N/A',
    noFails: 'No failed checklist items.',
    topProblems: 'Top Problem Assets', problemsHelp: 'Ranked by overdue + checklist fails + average delay.',
    byCategory: 'By Category', byDepartment: 'By Department', weakest: 'Weakest',
    noData: 'No data for this dimension.',
    dueThisWeek: 'Due This Week', neverMaintained: 'Never Maintained', avgDaysLate: 'Avg Days Late',
    approvalBacklog: 'Approval Backlog', avgApprovalWait: 'avg wait', forecast: 'Load Forecast (next 30d)', tasksDue: 'tasks due',
    byTechnician: 'Completion by Technician', completed: 'completed', technician: 'Technician',
    assets: 'assets', tasks: 'tasks', days: 'days', noTasks: 'No PM tasks in this period.',
    insights: 'Key Insights', unassigned: 'Unassigned',
  },
  rr: {
    title: 'Routine Roster',
    boardTab: 'Today board', templatesTab: 'Templates',
    todayBtn: 'Today', readOnlyHint: 'History — read only',
    needsMyAction: 'Needs my action', otherOrders: 'Other orders',
    noOrders: 'No routine orders for this day.',
    noTemplates: 'No daily routines set up yet.',
    noTemplatesHint: 'Templates create one order per day automatically — e.g. welcome drinks, welcome fruit, turndown gifts.',
    setupTemplates: '+ Set up routine templates',
    due: 'due', qty: 'Qty',
    // statuses
    pending: 'Pending', sentStatus: 'Sent', acceptedStatus: 'Accepted',
    deliveredStatus: 'Delivered', confirmedStatus: 'Confirmed', cancelledStatus: 'Cancelled',
    // timestamps line
    sentAt: 'Sent', acceptedAt: 'Accepted', deliveredAt: 'Delivered', confirmedAt: 'Confirmed',
    // actions / forms
    quantity: 'Quantity', quantityPh: 'e.g. 20',
    rooms: 'Rooms (one per line or comma-separated)',
    roomsPh: '101\n102\n104: mango',
    roomsHint: 'Add ": item" after a room number to override the item, e.g. "104: mango"',
    notePh: 'Note (optional)',
    sendOrder: 'Send order', acceptOrder: 'Accept order', markDelivered: 'Mark delivered',
    confirmReceived: 'Confirm received', cancelOrder: 'Cancel',
    confirmCancelOrder: 'Cancel this order?',
    roomChecklist: 'Room checklist',
    roomsDone: (d: number, t: number) => `${d}/${t} rooms`,
    quantityRequired: 'Enter a quantity.', roomsRequired: 'Add at least one room.',
    orderSent: 'Order sent', orderAccepted: 'Order accepted', orderDelivered: 'Marked as delivered',
    orderConfirmed: 'Receipt confirmed', orderCancelled: 'Order cancelled',
    // templates view
    addTemplate: 'Add template', editTemplate: 'Edit template', newTemplate: 'New template',
    name: 'Name (EN)', namePh: 'e.g. Welcome drinks', nameTh: 'Name (Thai, optional)',
    requestDept: 'Requesting department', fulfillDept: 'Fulfilling department',
    orderType: 'Order type', bulk: 'Bulk (single delivery)', perRoom: 'Per room (room checklist)',
    bulkShort: 'Bulk', perRoomShort: 'Per room',
    dueTime: 'Due time', defaultItem: 'Default item', defaultItemPh: 'e.g. Fruit plate',
    itemByWeekday: 'Item varies by weekday',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    activeLabel: 'Active (shown in the order menu)', inactiveBadge: 'Inactive',
    save: 'Save', cancel: 'Cancel', delete: 'Delete',
    nameRequired: 'Template name is required.',
    sameDeptError: 'Requesting and fulfilling department must differ.',
    confirmDeleteTemplate: 'Delete this template? Past orders are kept.',
    templateSaved: 'Template updated', templateAdded: 'Template added', templateDeleted: 'Template deleted',
    // report
    reportTab: 'Generate Report', reportTitle: 'Routine Roster Report',
    reportDaily: 'Daily', reportWeekly: 'Weekly', reportPeriod: 'Period',
    reportPrint: 'Print / Save PDF', reportNoData: 'No orders in this period.',
    reportDate: 'Date', reportRoutine: 'Routine', reportItem: 'Item', reportQty: 'Qty',
    reportRooms: 'Rooms', reportFrom: 'Requested by', reportTo: 'Fulfilled by', reportStatus: 'Status',
    reportSummary: 'Summary by item', reportTotal: 'Total',
    reportGeneratedBy: 'Generated by', reportGeneratedAt: 'Generated', reportForAccounting: 'For Accounting records',
    reportVariants: 'Variants', reportTotalRooms: (n: number) => `${n} rooms`,
    // ── order-ahead scheduling ──
    tomorrowBtn: 'Tomorrow',
    orderByOn: (close: string, day: string) => `Order by ${close} ${day}`,
    readyByOn: (due: string, day: string) => `Ready by ${due} ${day}`,
    today: 'today', tomorrow: 'tomorrow',
    windowPassed: 'Order window passed',
    lateTag: 'Late',
    toPlaceForTomorrow: (n: number) => `${n} ${n === 1 ? 'order' : 'orders'} to place for tomorrow`,
    toPlaceForDate: (n: number, day: string) => `${n} ${n === 1 ? 'order' : 'orders'} to place for ${day}`,
    // ── bulk unit ──
    quantityUnit: (unit: string) => `Quantity (${unit})`,
    // ── per-room variants ──
    pickRooms: 'Pick rooms', tapToAssign: 'Tap a room to add it; tap again to cycle its variant.',
    roomGridSummary: (parts: string, total: number) => `${parts} · ${total} ${total === 1 ? 'room' : 'rooms'}`,
    noVariantRooms: 'Select at least one room.',
    clearRooms: 'Clear',
    variantFor: (room: string) => `Variant for ${room}`,
    // ── PIC ──
    personInCharge: 'Person in charge',
    picWholeDept: 'Whole department', picSpecificPeople: 'Specific people',
    picNoneSelected: 'Select at least one person.',
    picSelectPeople: 'Select people',
    // ── timeline ──
    timeline: 'Timeline', timelineEmpty: 'No events yet.',
    evSent: 'placed the order', evAccepted: 'accepted', evDelivered: 'marked delivered',
    evConfirmed: 'confirmed receipt', evCancelled: 'cancelled', evRoomDelivered: 'delivered',
    evPicChanged: 'reassigned person in charge',
    someone: 'Someone',
    // ── mute ──
    muteRoutine: 'Mute reminders for this routine (for me)',
    unmuteRoutine: 'Unmute reminders for this routine',
    muted: 'Muted', muteToggleFailed: 'Could not update mute.',
    // ── template editor (new) ──
    perRoomVariants: 'Per room with variants', perRoomVariantsShort: 'Variants',
    unitLabel: 'Unit label (bulk)', unitLabelPh: 'e.g. gallon',
    variantsEditor: 'Variants', addVariant: 'Add variant',
    variantCode: 'Code', variantLabel: 'Label (EN)', variantLabelTh: 'Label (TH)',
    variantsRequired: 'Add at least one variant for this order type.',
    orderOpen: 'Order window opens', orderClose: 'Order window closes',
    remindAt: 'Reminder time (optional)',
  },
  roles: {
    super_admin: 'Super Admin', manager: 'Manager', staff: 'Staff',
  },
  common: {
    loading: 'Loading...', back: 'Back',
    mobileView: 'Mobile View', desktopView: 'Desktop View',
    switchToDesktop: 'Switch to Desktop View', switchToMobile: 'Switch to Mobile View',
    language: 'EN',
  },
} as const

// Widen the `as const` English shape: string/number literals -> primitives,
// functions preserved, nesting recursed, readonly stripped. This lets the Thai
// translation object satisfy the same structure without literal-type mismatches.
type DeepWiden<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends object
    ? { -readonly [K in keyof T]: DeepWiden<T[K]> }
    : T extends string ? string
    : T extends number ? number
    : T extends boolean ? boolean
    : T
type Translations = DeepWiden<typeof en>

const th: Translations = {
  nav: {
    dashboard: 'แดชบอร์ด', cases: 'เคส', newCase: 'รายงานใหม่',
    calendar: 'ปฏิทิน', performance: 'ประสิทธิภาพ',
    maintenance: 'การบำรุงรักษาเชิงป้องกัน',
    routineRoster: 'งานประจำวัน',
    notifications: 'การแจ้งเตือน', users: 'ผู้ใช้งาน', settings: 'การตั้งค่า',
    signOut: 'ออกจากระบบ', home: 'หน้าหลัก', alerts: 'แจ้งเตือน',
  },
  login: {
    title: 'เข้าสู่ระบบ', signInAs: 'เข้าสู่ระบบในฐานะ', superAdmin: 'ผู้ดูแลระบบ',
    manager: 'ผู้จัดการ', staff: 'พนักงาน', department: 'แผนก',
    selectDept: 'เลือกแผนกของคุณ', username: 'ชื่อผู้ใช้',
    email: 'อีเมล', password: 'รหัสผ่าน',
    enterUsername: 'กรอกชื่อผู้ใช้', enterEmail: 'กรอกอีเมล',
    enterPassword: 'กรอกรหัสผ่าน',
    footer: 'Kaizen System · สำหรับภายในเท่านั้น',
    noDeptError: 'กรุณาเลือกแผนกของคุณ',
    companyCode: 'รหัสบริษัท',
    enterCompanyCode: 'รหัสบริษัทของคุณ',
    noCompanyCode: 'กรุณากรอกรหัสบริษัท',
    forgotPassword: 'ลืมรหัสผ่าน?',
    backToLogin: 'กลับไปเข้าสู่ระบบ',
    resetTitle: 'รีเซ็ตรหัสผ่าน',
    resetSubtitle: 'กรอกอีเมลของคุณ เราจะส่งลิงก์รีเซ็ตให้',
    sendResetLink: 'ส่งลิงก์รีเซ็ต',
    resetSent: 'กรุณาตรวจสอบอีเมลของคุณสำหรับลิงก์รีเซ็ตรหัสผ่าน',
    contactManager: 'ติดต่อผู้จัดการหรือฝ่าย HR เพื่อรีเซ็ตรหัสผ่านของคุณ',
    emailNotRegistered: 'อีเมลนี้ไม่ได้ลงทะเบียนในระบบ กรุณาติดต่อผู้ดูแลระบบหรือฝ่าย HR',
  },
  dashboard: {
    title: 'แดชบอร์ด', welcome: 'ยินดีต้อนรับกลับ',
    totalCases: 'เคสทั้งหมด', open: 'เปิดอยู่', inProgress: 'กำลังดำเนินการ',
    resolved: 'แก้ไขแล้ว', waitingApproval: 'รอการอนุมัติ',
    caseOverview: 'ภาพรวมเคส', casesShort: 'เคส', totalShort: 'ทั้งหมด',
    monthlyCases: 'เคสรายเดือน',
    criticalBanner: (n: number) => `มี ${n} เคสวิกฤตที่ต้องการการแก้ไขด่วน`,
    slaBanner: (n: number) => `${n} เคสเกินกำหนด`,
    view: 'ดู', recentCases: 'เคสล่าสุด', viewAll: 'ดูทั้งหมด',
    noCases: 'ยังไม่มีเคส', casesByDept: 'เคสตามแผนก',
    noData: 'ไม่มีข้อมูล', newCase: 'รายงานใหม่',
    avgResolution: 'เวลาแก้ไขเฉลี่ย', resolutionRate: 'อัตราการแก้ไข',
    casesThisMonth: 'เคสเดือนนี้', overdueSLA: 'เกินกำหนด',
    recurringIssues: 'ปัญหาซ้ำ',
    deptPerformance: 'ประสิทธิภาพแผนก',
    openCases: 'เคสที่เปิดอยู่', avgDays: 'เฉลี่ย (วัน)', overdue: 'เกินกำหนด',
    casesByCategory: 'เคสตามประเภท',
  },
  cases: {
    title: 'เคส', newCase: 'รายงานใหม่',
    search: 'ค้นหาด้วยคำค้น เลขซีเรียล หรือหมายเลขเคส...', allStatuses: 'ทุกสถานะ',
    allPriorities: 'ทุกระดับ', noFound: 'ไม่พบเคส',
    adjustFilters: 'ลองปรับตัวกรองหรือสร้างเคสใหม่',
    caseNo: 'หมายเลข', titleCol: 'ชื่อ', dept: 'แผนก',
    priority: 'ระดับ', status: 'สถานะ', age: 'อายุ', duration: 'ระยะเวลา',
    export: 'ส่งออก', due: 'กำหนดส่ง',
    caseCount: (n: number) => `${n} เคส`,
    allCategories: 'ทุกประเภท', slaBreached: 'เกินกำหนด',
    category: 'ประเภท',
  },
  createCase: {
    title: 'รายงานปัญหา', subtitle: 'บันทึกปัญหาเพื่อการติดตามและแก้ไข',
    caseDetails: 'รายละเอียดเคส', department: 'แผนก',
    problemTitle: 'ชื่อปัญหา', problemPlaceholder: 'เช่น เก้าอี้แตกในห้องอาหาร โต๊ะ 5',
    description: 'รายละเอียด', descPlaceholder: 'อธิบายปัญหาโดยละเอียด รวมถึงสถานที่ ความรุนแรง และบริบทที่เกี่ยวข้อง...',
    priority: 'ระดับความสำคัญ', photoEvidence: 'หลักฐานภาพถ่าย',
    photoSubtitle: 'อัปโหลดภาพถ่ายปัญหาเพื่อให้ทีมเข้าใจสถานการณ์',
    submit: 'ส่งเคส', cancel: 'ยกเลิก',
    fillRequired: 'กรุณากรอกข้อมูลที่จำเป็นให้ครบ',
    created: (n: string) => `สร้างเคส ${n} สำเร็จ!`,
    failed: 'ไม่สามารถสร้างเคสได้ กรุณาลองใหม่',
    dueDate: 'วันกำหนดส่ง', optional: '(ไม่บังคับ)', addPhotos: 'เพิ่มรูปภาพ',
    category: 'ประเภท', selectCategory: 'เลือกประเภท',
    recurring: 'ปัญหาที่เกิดซ้ำ', recurringHint: 'เลือกหากปัญหานี้เคยเกิดขึ้นมาก่อน',
  },
  status: {
    open: 'เปิด', assigned: 'มอบหมายแล้ว', in_progress: 'กำลังดำเนินการ',
    pending_manager_approval: 'รออนุมัติ',
    pending_admin_approval: 'รออนุมัติ',
    closed: 'ปิด', reopened: 'เปิดใหม่',
  },
  priority: { low: 'ต่ำ', medium: 'ปานกลาง', high: 'สูง', critical: 'วิกฤต' },
  users: {
    title: 'ผู้ใช้งาน', addUser: 'เพิ่มผู้ใช้', accounts: 'บัญชี',
    superAdmins: 'ผู้ดูแลระบบ', managers: 'ผู้จัดการ', staff: 'พนักงาน',
    createTitle: 'สร้างผู้ใช้ใหม่', createSubtitle: 'เพิ่มบัญชีพนักงาน ผู้จัดการ หรือผู้ดูแลระบบ',
    fullName: 'ชื่อ-นามสกุล', fullNamePlaceholder: 'เช่น สมชาย แก้วขาม',
    username: 'ชื่อผู้ใช้', emailAddress: 'อีเมล',
    emailPlaceholder: 'เช่น name@nanirand.com', password: 'รหัสผ่าน',
    minPassword: 'อย่างน้อย 6 ตัวอักษร', createAccount: 'สร้างบัญชี', cancel: 'ยกเลิก',
    inactive: '(ปิดใช้งาน)', noYet: (label: string) => `ยังไม่มี${label}`,
    confirmDeactivate: (active: boolean) => `ต้องการ${active ? 'ปิดใช้งาน' : 'เปิดใช้งาน'}บัญชีนี้?`,
    confirmDelete: (name: string) => `ลบบัญชีของ ${name} ถาวร? ไม่สามารถกู้คืนได้`,
    deactivated: 'ปิดใช้งานบัญชีแล้ว', reactivated: 'เปิดใช้งานบัญชีแล้ว', deleted: 'ลบบัญชีแล้ว',
    created: 'สร้างบัญชีสำเร็จ', failedCreate: 'ไม่สามารถสร้างผู้ใช้ได้',
    failedStatus: 'ไม่สามารถอัปเดตสถานะบัญชีได้', failedDelete: 'ไม่สามารถลบบัญชีได้',
    fillRequired: 'กรุณากรอกชื่อและรหัสผ่าน',
    usernameRequired: 'กรุณากรอกชื่อผู้ใช้สำหรับพนักงาน',
    emailRequired: 'กรุณากรอกอีเมลสำหรับผู้จัดการและผู้ดูแลระบบ',
    minPwd: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    dept: 'แผนก', roleLabel: 'บทบาท',
    editTitle: 'แก้ไขผู้ใช้', editSubtitle: 'อัปเดตข้อมูลผู้ใช้หรือรีเซ็ตรหัสผ่าน',
    resetPassword: 'รีเซ็ตรหัสผ่าน', keepCurrent: '(เว้นว่างเพื่อคงรหัสผ่านเดิม)',
    saveChanges: 'บันทึกการเปลี่ยนแปลง',
  },
  notifications: {
    title: 'การแจ้งเตือน', markAllRead: 'ทำเครื่องหมายอ่านทั้งหมด',
    noNotifications: 'ไม่มีการแจ้งเตือน', viewAll: 'ดูการแจ้งเตือนทั้งหมด',
    allTab: 'ทั้งหมด', unreadTab: 'ยังไม่อ่าน', allRead: 'ทำเครื่องหมายอ่านทั้งหมดแล้ว',
    empty: 'คุณอ่านทุกอย่างแล้ว!',
    today: 'วันนี้', yesterday: 'เมื่อวาน', thisWeek: 'สัปดาห์นี้', older: 'เก่ากว่า',
  },
  settings: {
    title: 'การตั้งค่า', theme: 'ธีมสี', themeSubtitle: 'ปรับแต่งรูปแบบสีของแอป',
    presets: 'พรีเซ็ตพิเศษ', primaryColor: 'สีหลัก', accentColor: 'สีเน้น',
    sidebarColor: 'สีแถบเมนู', applyTheme: 'ใช้ธีม', applying: 'กำลังใช้งาน...',
    themeApplied: 'อัปเดตธีมสำเร็จ!', failedTheme: 'ไม่สามารถอัปเดตธีมได้',
    adminOnly: 'การตั้งค่าธีมสามารถเปลี่ยนได้โดยผู้ดูแลระบบเท่านั้น',
    changePassword: 'เปลี่ยนรหัสผ่าน', passwordSubtitle: 'อัปเดตรหัสผ่านเข้าสู่ระบบของคุณ',
    currentPassword: 'รหัสผ่านปัจจุบัน', newPassword: 'รหัสผ่านใหม่',
    confirmPassword: 'ยืนยันรหัสผ่านใหม่', updatePassword: 'อัปเดตรหัสผ่าน',
    updating: 'กำลังอัปเดต...', passwordUpdated: 'อัปเดตรหัสผ่านสำเร็จ!',
    failedPassword: 'ไม่สามารถอัปเดตรหัสผ่านได้', mismatch: 'รหัสผ่านใหม่ไม่ตรงกัน',
    accountInfo: 'ข้อมูลบัญชี', name: 'ชื่อ', role: 'บทบาท', dept: 'แผนก',
    scoringTitle: 'การให้คะแนนประสิทธิภาพ',
    scoringSubtitle: 'ปรับน้ำหนักของแต่ละตัวชี้วัดที่มีผลต่อคะแนนประสิทธิภาพ น้ำหนักเป็นค่าสัมพัทธ์ ไม่จำเป็นต้องรวมกันได้ 100',
    scoringStaffGroup: 'คะแนนพนักงาน', scoringManagerGroup: 'คะแนนผู้จัดการ',
    scoringIncludePms: 'รวมการบำรุงรักษาเชิงป้องกัน (PMS) ในคะแนน',
    scoringIncludeRr: 'รวมงานประจำ (RR) ในคะแนน',
    scoringWeightHint: 'น้ำหนักเป็นค่าสัมพัทธ์ สัดส่วนที่แสดงคือน้ำหนักเทียบกับผลรวมของตัวชี้วัดที่ใช้งาน',
    scoringSave: 'บันทึกการให้คะแนน', scoringReset: 'รีเซ็ตเป็นค่าเริ่มต้น', scoringSaved: 'บันทึกการให้คะแนนประสิทธิภาพแล้ว',
  },
  caseDetail: {
    caseInfo: 'ข้อมูลเคส', createdBy: 'สร้างโดย', reportedOn: 'รายงานเมื่อ',
    translate: 'แปล', showOriginal: 'ดูต้นฉบับ',
    machineTranslation: 'แปลด้วยเครื่อง', translateFailed: 'แปลไม่สำเร็จ — กรุณาลองใหม่',
    recurringChronic: (n: number) => `ปัญหาเรื้อรัง · ${n} รายงาน`,
    recurringRecurring: (n: number) => `ปัญหาเกิดซ้ำ · ${n} รายงาน`,
    recurringOnce: (n: number) => `เคยรายงานแล้ว · ${n} รายงาน`,
    recurringChronicAdvice: 'ปัญหาประเภทเดียวกันนี้ถูกรายงานมากกว่า 3 ครั้งที่สถานที่นี้ ควรพิจารณาแก้ไขถาวรหรือเปลี่ยนใหม่',
    recurringRecurringAdvice: 'ปัญหาประเภทเดียวกันนี้ถูกรายงานหลายครั้งที่สถานที่นี้ ควรติดตามอย่างใกล้ชิด',
    recurringOnceAdvice: 'ปัญหาประเภทเดียวกันนี้เคยถูกรายงานมาก่อนหนึ่งครั้งที่สถานที่นี้',
    recurringFlagged: 'ระบุว่าเกิดซ้ำ',
    recurringFlaggedAdvice: 'ผู้แจ้งระบุว่าปัญหานี้เคยเกิดขึ้นมาก่อน',
    openedBy: 'เปิดโดย:', inCharge: 'ผู้รับผิดชอบ:', dueLabel: 'กำหนดเสร็จ:',
    removedFromCompany: 'ไม่ได้อยู่กับบริษัทแล้ว',
    addDueDate: '+ เพิ่มกำหนดเสร็จ', noDueDate: 'ไม่มีกำหนดเสร็จ', notifyAll: 'แจ้งทั้งหมด',
    lastUpdated: 'อัปเดตล่าสุด', duration: 'ระยะเวลา',
    proposedSolution: 'แนวทางแก้ไขที่เสนอ', assignedDepts: 'แผนกที่เกี่ยวข้อง',
    timeline: 'ไทม์ไลน์', problemPhotos: 'ภาพถ่ายปัญหา', resolutionPhotos: 'ภาพถ่ายการแก้ไข',
    noPhotos: 'ไม่มีภาพถ่าย',
    assignDepts: 'มอบหมายแผนก', proposeSolution: 'เสนอแนวทางแก้ไข',
    solutionPlaceholder: 'อธิบายแนวทางแก้ไขที่เสนอ...',
    assignBtn: 'ยืนยัน',
    resolveCase: 'แก้ไขเคส', resolutionDesc: 'รายละเอียดการแก้ไข',
    resolutionPlaceholder: 'อธิบายวิธีการแก้ไขปัญหา...',
    uploadEvidence: 'อัปโหลดภาพถ่ายหลักฐาน', submitResolution: 'ส่งการแก้ไข',
    approveTitle: 'อนุมัติการแก้ไข', approveDesc: 'อนุมัติและส่งต่อให้ผู้ดูแลระบบปิดเคส',
    approveBtn: 'อนุมัติการแก้ไข',
    closeTitle: 'ปิดเคส', closeDesc: 'ปิดเคสนี้หลังจากตรวจสอบการแก้ไขแล้ว', closeBtn: 'ปิดเคส',
    reopenTitle: 'เปิดเคสใหม่', reopenDesc: 'เปิดเคสใหม่หากปัญหายังไม่ได้รับการแก้ไขอย่างสมบูรณ์', reopenBtn: 'เปิดเคสใหม่',
    deleteTitle: 'ลบเคส', deleteDesc: 'ลบเคสนี้และข้อมูลทั้งหมดที่เกี่ยวข้องถาวร', deleteBtn: 'ลบเคส',
    confirmClose: 'ปิดเคสนี้? จะถือว่าแก้ไขเสร็จสมบูรณ์',
    confirmReopen: 'เปิดเคสนี้ใหม่?',
    confirmDelete: 'ลบเคสนี้ถาวร? ไม่สามารถกู้คืนได้',
    selectDepts: 'กรุณาเลือกอย่างน้อยหนึ่งแผนก',
    provideSolution: 'กรุณาระบุแนวทางแก้ไขที่เสนอ',
    provideResolution: 'กรุณาระบุรายละเอียดการแก้ไข',
    notFound: 'ไม่พบเคส',
    changePriority: 'เปลี่ยนระดับความสำคัญ',
    changePriorityBtn: 'อัปเดตระดับความสำคัญ',
    priorityChanged: (p: string) => `เปลี่ยนระดับความสำคัญเป็น ${p} แล้ว`,
    priorityChangedNotif: (n: string, p: string) => `ระดับความสำคัญของเคส ${n} ถูกเปลี่ยนเป็น ${p} โดยผู้ดูแลระบบ`,
    editCase: 'แก้ไขเคส', assignedTo: 'มอบหมายให้:',
    internalNotes: 'บันทึกภายใน', noNotes: 'ยังไม่มีบันทึก เพิ่มด้านล่าง',
    notePlaceholder: 'เพิ่มบันทึกภายใน...',
    mentionHint: 'พิมพ์ @ เพื่อกล่าวถึงและแจ้งเตือนเพื่อนร่วมงาน',
    postNote: 'บันทึก', noteCount: (n: number) => `${n} บันทึก`,
    noActivity: 'ยังไม่มีกิจกรรม',
    openFor: 'เปิดมาแล้ว', dueDateLabel: 'กำหนดส่ง', daysLeftLabel: 'วันที่เหลือ',
    notSet: 'ไม่ได้กำหนด', dueToday: 'ครบกำหนดวันนี้',
    overdueBy: (n: number) => `เลยกำหนด ${n} วัน`,
    daysLeftCount: (n: number) => `เหลือ ${n} วัน`,
    currentPriority: 'ปัจจุบัน:',
    editModalTitle: 'แก้ไขเคส', fieldTitle: 'ชื่อเรื่อง', fieldDescription: 'รายละเอียด',
    fieldDueDate: 'วันกำหนดส่ง', fieldStatus: 'สถานะ',
    statusManualNote: 'การเปลี่ยนสถานะด้วยตนเองจะถูกบันทึกในไทม์ไลน์',
    saveChanges: 'บันทึกการเปลี่ยนแปลง', cancelBtn: 'ยกเลิก',
    assignStaff: 'มอบหมายพนักงาน', selectNewPriority: 'เลือกระดับใหม่',
    selectDept: 'เลือกแผนก', selectStatus: 'เลือกสถานะ',
    noStaffAssigned: 'ยังไม่มีพนักงานที่ได้รับมอบหมาย',
    addDept: 'เพิ่มแผนก...', addDeptBtn: 'เพิ่ม',
    recurringBadge: 'ปัญหาที่เกิดซ้ำ', printPdf: 'พิมพ์ / PDF',
    relatedCases: 'เคสที่เกี่ยวข้อง', linkCase: 'เชื่อมโยงเคส...', noRelatedCases: 'ไม่มีเคสที่เกี่ยวข้อง',
    unlinkCase: 'ยกเลิกการเชื่อมโยง',
  },
  categories: {
    maintenance: 'การซ่อมบำรุง', cleanliness: 'ความสะอาด', safety: 'ความปลอดภัย',
    guest_complaint: 'ข้อร้องเรียนแขก', equipment: 'อุปกรณ์', other: 'อื่นๆ',
    preventive_maintenance: 'การบำรุงรักษาเชิงป้องกัน',
  },
  perf: {
    overallTitle: 'คะแนนประสิทธิภาพโดยรวม',
    staffCard: 'เกณฑ์ประเมินพนักงาน', leadershipCard: 'เกณฑ์ประเมินภาวะผู้นำ',
    tapHint: 'แตะที่ตัวชี้วัดเพื่อดูวิธีการคำนวณ',
    scoreOutOf: 'คะแนนเต็ม 100', weight: 'น้ำหนัก',
    closed: 'ปิดแล้ว', overdue: 'เกินกำหนด', reopened: 'เปิดใหม่', avg: 'เฉลี่ย',
    activeDays: 'วันที่ใช้งาน', activeDay: 'วันที่ใช้งาน', actions: 'กิจกรรม',
    noApprovals: 'ยังไม่มีการอนุมัติ', noClosed: 'ยังไม่มีเคสที่ปิด',
    resolutionRate: 'อัตราการแก้ไข',
    resolutionRateInfo: 'สัดส่วนของเคสที่คุณรับผิดชอบ (รายงานหรือเป็นผู้รับผิดชอบ) ที่คุณแก้ไขและปิดเรียบร้อยแล้ว',
    onTime: 'ตรงตามกำหนดเวลา',
    onTimeInfo: 'สัดส่วนของเคสที่ยังไม่เกินกำหนด — สะท้อนความน่าเชื่อถือในการส่งมอบงานตรงเวลา',
    speed: 'ความเร็วในการแก้ไข',
    speedInfo: 'ความเร็วเฉลี่ยในการแก้ไขเคส วัดเทียบกับเป้าหมาย 48 ชั่วโมง หากแก้ไขภายใน 48 ชั่วโมงจะได้คะแนนเต็ม',
    quality: 'คุณภาพ',
    qualityInfo: 'การแก้ไขมีคุณภาพเพียงใด — สัดส่วนของเคสที่แก้ไขแล้วและไม่ถูกเปิดใหม่ ยิ่งเปิดใหม่น้อยยิ่งคุณภาพสูง',
    engagement: 'ความมีส่วนร่วม',
    engagementInfo: 'คุณมีส่วนร่วมกับ Kaizen มากเพียงใด — จำนวนวันที่ใช้งานใน 30 วันที่ผ่านมารวมกับกิจกรรมในระบบ (การอัปเดต ความคิดเห็น การแก้ไข) วัดตลอดทั้งเดือน การไม่เข้าระบบเพียงวันเดียวจึงแทบไม่มีผล',
    approval: 'ความรวดเร็วในการอนุมัติ',
    approvalInfo: 'คุณอนุมัติเคสที่ทีมส่งมาได้เร็วเพียงใด — เวลาเฉลี่ยจากการแก้ไขของพนักงานจนถึงการอนุมัติของคุณ (เป้าหมาย: ภายใน 24 ชั่วโมง) ยิ่งปลดล็อกงานเร็วยิ่งได้คะแนนสูง',
    teamRes: 'อัตราการแก้ไขของทีม',
    teamResInfo: 'สัดส่วนของเคสในแผนกของคุณที่แก้ไขและปิดเรียบร้อยแล้ว — ผลงานโดยรวมของทีม',
    teamSla: 'สุขภาพความตรงเวลาของทีม',
    teamSlaInfo: 'สัดส่วนของเคสในแผนกของคุณที่ยังไม่เกินกำหนด — สะท้อนการดูแลให้ทีมทำงานตามกำหนดเวลา',
    leadership: 'ภาวะผู้นำและคุณภาพ',
    leadershipInfo: 'การผสมผสานระหว่างคุณภาพงาน (เคสถูกเปิดใหม่น้อย) และการควบคุมงานค้าง (เคสเกินกำหนดน้อย) ในแผนกของคุณ — สะท้อนความสมบูรณ์ของกระบวนการทำงานของทีม',
    oversight: 'การกำกับดูแลและการมีส่วนร่วม',
    oversightInfo: 'คุณใช้ Kaizen ในการบริหารมากเพียงใด — จำนวนวันที่ใช้งานใน 30 วันที่ผ่านมารวมกับกิจกรรมในระบบ (การมอบหมาย การอนุมัติ ความคิดเห็น) การขาดเพียงวันเดียวแทบไม่มีผล แต่การขาดหายต่อเนื่องจะทำให้คะแนนลดลง',
    pmsScore: 'ความน่าเชื่อถือ PMS',
    pmsScoreInfo: 'งานบำรุงรักษาเชิงป้องกันเสร็จตรงเวลาเพียงใด — สัดส่วนของงาน PM ที่เกี่ยวข้องซึ่งเสร็จภายในกำหนด ยิ่งสูงยิ่งหมายความว่าการดูแลอุปกรณ์เป็นไปตามกำหนด',
    rrScore: 'ความน่าเชื่อถืองานประจำ',
    rrScoreInfo: 'งานประจำตามตารางถูกดำเนินการตรงเวลาเพียงใด — สัดส่วนของออเดอร์ที่ดำเนินการซึ่งส่งหรือยืนยันภายในเวลาที่กำหนด ยิ่งสูงยิ่งหมายความว่าการส่งมอบงานประจำเป็นไปตามกำหนด',
  },
  calendar: {
    allDepts: 'ทุกแผนก', filterByDept: 'กรองตามแผนก',
    today: 'วันนี้', more: 'เพิ่มเติม', priorityLabel: 'ระดับ:',
    casesCalendar: 'ปฏิทินเคส',
    combined: 'รวม', casePriority: 'ระดับความสำคัญเคส:', pmStatus: 'สถานะ PM:',
    routine: 'งานประจำวัน', rrStatus: 'สถานะงานประจำ:',
    noMaintenance: 'ไม่มีงานบำรุงรักษาที่กำหนดไว้', nothingDay: 'ไม่มีรายการในวันนี้',
  },
  pm: {
    scheduler: 'ระบบกำหนดการบำรุงรักษาเชิงป้องกัน', open: 'เปิด',
    addAsset: 'อุปกรณ์', searchAssets: 'ค้นหาชื่อ/แท็กอุปกรณ์ หมายเลขซีเรียล รุ่น…',
    noAssets: 'ยังไม่มีอุปกรณ์ที่ลงทะเบียน', noAssetsFiltered: 'ไม่มีอุปกรณ์ตรงกับตัวกรอง',
    registerFirst: '+ ลงทะเบียนอุปกรณ์ชิ้นแรก', next: 'ครั้งถัดไป',
    good: 'เป็นปัจจุบัน', dueSoon: 'ใกล้ถึงกำหนด', overdue: 'เลยกำหนด', notScheduled: 'ยังไม่กำหนด', inactiveStatus: 'ปิดใช้งาน',
    scheduled: 'กำหนดไว้', inProgress: 'กำลังดำเนินการ', awaitingApproval: 'รออนุมัติ', done: 'เสร็จสิ้น',
    editAsset: 'แก้ไขอุปกรณ์', registerAsset: 'ลงทะเบียนอุปกรณ์',
    assetName: 'ชื่อ / รหัสอุปกรณ์', assetNamePh: 'เช่น แอร์ล็อบบี้ #1',
    equipmentType: 'ประเภทอุปกรณ์', selectType: '— เลือก —',
    location: 'สถานที่ / โซน', locationPh: 'อาคาร / ชั้น / ห้อง',
    serialNo: 'หมายเลขเครื่อง', model: 'รุ่น',
    responsibleDept: 'แผนกที่รับผิดชอบ', none: '— ไม่มี —',
    frequency: 'ความถี่', customEvery: 'กำหนดเอง (ทุก N วัน)', everyNDays: 'ทุก N วัน',
    estMinutes: 'เวลาโดยประมาณ (นาที)', optional: 'ไม่บังคับ',
    lastMaint: 'บำรุงรักษาล่าสุด', nextMaint: 'บำรุงรักษาครั้งถัดไป', purchaseDate: 'วันที่ซื้อ',
    checklist: 'รายการตรวจสอบ (หนึ่งรายการต่อบรรทัด)',
    checklistPh: 'ทำความสะอาด / เปลี่ยนไส้กรอง\nตรวจสอบน้ำยา\nทดสอบเทอร์โมสตัท',
    notesInstr: 'หมายเหตุ / คำแนะนำ', activeInclude: 'ใช้งาน (รวมในการจัดตาราง)',
    save: 'บันทึก', register: 'ลงทะเบียน', cancel: 'ยกเลิก', delete: 'ลบ',
    assetNameRequired: 'กรุณาระบุชื่ออุปกรณ์', assetSaved: 'อัปเดตอุปกรณ์แล้ว', assetAdded: 'เพิ่มอุปกรณ์แล้ว',
    confirmDeleteAsset: 'ลบอุปกรณ์นี้? ประวัติการบำรุงรักษาจะถูกลบไปด้วย',
    checklistTitle: 'รายการตรวจสอบ', pass: 'ผ่าน', fail: 'ไม่ผ่าน', na: 'ไม่เกี่ยว',
    readings: 'ค่าที่อ่านได้', parts: 'อะไหล่', findings: 'สิ่งที่พบ', performed: 'ดำเนินการเมื่อ',
    readingsLabel: 'ค่าที่อ่านได้ / การวัด', readingsPh: 'เช่น 12°C, 220V',
    partsLabel: 'อะไหล่ / วัสดุสิ้นเปลืองที่ใช้', findingsLabel: 'สิ่งที่พบ / หมายเหตุ',
    start: 'เริ่ม', complete: 'เสร็จสิ้น', approve: 'อนุมัติ', return: 'ส่งกลับ',
    rejectPrompt: 'เหตุผลในการส่งงานนี้กลับให้ช่าง?',
    recorded: 'บันทึกการบำรุงรักษาแล้ว', approvedToast: 'อนุมัติการบำรุงรักษาแล้ว', returnedToast: 'ส่งกลับให้ช่างแล้ว',
    awaitingNote: 'รออนุมัติ', awaitingBy: 'โดยผู้จัดการที่รับผิดชอบ / ผู้บริหารระดับสูง',
    startFirst: 'กรุณากด "เริ่ม" ก่อนบันทึกเช็คลิสต์',
    readingsPartsRequired: 'ต้องกรอกค่าที่อ่านได้ / การวัด และอะไหล่ / วัสดุสิ้นเปลือง ก่อนกดเสร็จสิ้น',
    confirmCompleteTitle: 'ยืนยันการบำรุงรักษานี้?',
    confirmCompleteMsg: 'กรุณายืนยันว่าเช็คลิสต์และค่าที่อ่านได้ถูกต้อง การดำเนินการนี้จะบันทึกการบำรุงรักษา',
    confirmComplete: 'ยืนยัน เสร็จสิ้น', confirmCancel: 'ยกเลิก',
    timeline: 'ไทม์ไลน์', tlScheduled: 'สร้างงาน', tlStarted: 'เริ่มงาน', tlCompleted: 'ทำเสร็จ', tlApproved: 'อนุมัติแล้ว',
    compliance: 'ความเป็นไปตามแผน', dueThisWeek: 'ครบกำหนดสัปดาห์นี้', doneThisMonth: 'เสร็จเดือนนี้', onTimeRate: 'อัตราตรงเวลา',
    setupScheduler: 'ตั้งค่าระบบกำหนดการ →',
    settingsTitle: 'การบำรุงรักษาเชิงป้องกัน — การตั้งค่า',
    settingsDesc: 'กฎการอนุมัติ การแจ้งเตือน และการยกระดับสำหรับงานบำรุงรักษา',
    requireApproval: 'ต้องมีการอนุมัติงานบำรุงรักษา',
    requireApprovalDesc: 'เมื่อเปิด งานที่ทำเสร็จจะรอให้ผู้จัดการแผนกที่รับผิดชอบ (หรือผู้บริหารระดับสูง) อนุมัติก่อนจึงจะเริ่มรอบถัดไป',
    dueSoonWindow: 'ช่วง "ใกล้ถึงกำหนด" (วัน)',
    dueSoonWindowDesc: 'อุปกรณ์จะเปลี่ยนเป็นสีเหลืองภายในกี่วันก่อนถึงกำหนดบำรุงรักษา',
    escalateAfter: 'ยกระดับเป็นเคสเมื่อเลยกำหนด (วัน)',
    escalateAfterDesc: 'งานที่เลยกำหนดตามจำนวนวันนี้จะสร้างเคสโดยอัตโนมัติ',
    autoEscalate: 'ยกระดับงานที่เลยกำหนดเป็นเคสอัตโนมัติ',
    autoEscalateDesc: 'สร้างเคสปกติ (ระดับสูง) เพื่อไม่ให้งานที่เลยกำหนดถูกลืม',
    saveSettings: 'บันทึกการตั้งค่า', settingsSaved: 'บันทึกการตั้งค่าการบำรุงรักษาแล้ว',
    typesTitle: 'การบำรุงรักษาเชิงป้องกัน — ประเภทอุปกรณ์',
    typesDesc: 'กำหนดประเภทอุปกรณ์ที่ใช้เมื่อลงทะเบียนอุปกรณ์ เฉพาะผู้บริหารระดับสูงเท่านั้นที่แก้ไขได้',
    newType: 'ประเภทใหม่', newTypePh: 'เช่น ปั๊มความร้อน', category: 'หมวดหมู่', add: 'เพิ่ม',
    noTypes: 'ยังไม่มีประเภทอุปกรณ์', loadDefaults: 'โหลดประเภทเริ่มต้น',
    on: 'เปิด', off: 'ปิด', activate: 'เปิดใช้งาน', deactivate: 'ปิดใช้งาน', rename: 'เปลี่ยนชื่อ',
    defaultsAdded: 'เพิ่มประเภทอุปกรณ์เริ่มต้นแล้ว', confirmDeleteType: 'ลบประเภทอุปกรณ์',
  },
  pmReport: {
    button: 'รายงาน',
    title: 'รายงานการบำรุงรักษาเชิงป้องกัน',
    subtitle: 'ภาพรวมสุขภาพการบำรุงรักษา',
    dateOfReport: 'วันที่ออกรายงาน',
    period: 'ช่วงเวลา', last30: '30 วันล่าสุด', last90: '90 วันล่าสุด', last180: '180 วันล่าสุด', last365: '12 เดือนล่าสุด',
    printSave: 'พิมพ์ / บันทึก PDF', close: 'ปิด',
    vs1m: 'เทียบ 1ด.', vs3m: 'เทียบ 3ด.', vs6m: 'เทียบ 6ด.',
    compliance: 'ความเป็นไปตามแผน PM', onTimeDone: 'เสร็จตรงเวลา', ofDue: 'ของงานที่ครบกำหนด',
    complianceHelp: 'งานที่เสร็จตรงเวลา ÷ งานที่ครบกำหนดในช่วงเวลา',
    overdue: 'เกินกำหนด', overdueTasks: 'งานเกินกำหนด', daysOverdue: 'วันสาย', neverPerformed: 'ไม่เคยทำ', missedBy: 'สายไป',
    noOverdue: 'ไม่มีงานเกินกำหนด — เยี่ยมมาก',
    checklistFails: 'รายการตรวจที่ไม่ผ่าน', tasksWithFail: 'งานที่มีรายการไม่ผ่าน ≥1', passItems: 'ผ่าน', failItems: 'ไม่ผ่าน', naItems: 'ไม่เกี่ยวข้อง',
    noFails: 'ไม่มีรายการตรวจที่ไม่ผ่าน',
    topProblems: 'อุปกรณ์ที่มีปัญหาสูงสุด', problemsHelp: 'จัดอันดับตามงานเกินกำหนด + รายการไม่ผ่าน + ความล่าช้าเฉลี่ย',
    byCategory: 'ตามหมวดหมู่', byDepartment: 'ตามแผนก', weakest: 'อ่อนที่สุด',
    noData: 'ไม่มีข้อมูลสำหรับมิตินี้',
    dueThisWeek: 'ครบกำหนดสัปดาห์นี้', neverMaintained: 'ไม่เคยบำรุงรักษา', avgDaysLate: 'สายเฉลี่ย (วัน)',
    approvalBacklog: 'งานรออนุมัติค้าง', avgApprovalWait: 'รอเฉลี่ย', forecast: 'พยากรณ์ภาระงาน (30 วันข้างหน้า)', tasksDue: 'งานครบกำหนด',
    byTechnician: 'งานเสร็จตามช่าง', completed: 'เสร็จ', technician: 'ช่าง',
    assets: 'อุปกรณ์', tasks: 'งาน', days: 'วัน', noTasks: 'ไม่มีงาน PM ในช่วงเวลานี้',
    insights: 'ข้อมูลเชิงลึกสำคัญ', unassigned: 'ไม่ได้มอบหมาย',
  },
  rr: {
    title: 'งานประจำวัน',
    boardTab: 'รายการวันนี้', templatesTab: 'แม่แบบ',
    todayBtn: 'วันนี้', readOnlyHint: 'ประวัติ — ดูได้อย่างเดียว',
    needsMyAction: 'งานที่ฉันต้องทำ', otherOrders: 'รายการอื่น ๆ',
    noOrders: 'ไม่มีรายการสั่งประจำวันสำหรับวันนี้',
    noTemplates: 'ยังไม่ได้ตั้งค่างานประจำวัน',
    noTemplatesHint: 'แม่แบบจะสร้างออเดอร์ให้อัตโนมัติวันละหนึ่งรายการ เช่น เครื่องดื่มต้อนรับ ผลไม้ต้อนรับ ของขวัญเทิร์นดาวน์',
    setupTemplates: '+ ตั้งค่าแม่แบบงานประจำ',
    due: 'กำหนด', qty: 'จำนวน',
    // statuses
    pending: 'รอส่ง', sentStatus: 'ส่งออเดอร์แล้ว', acceptedStatus: 'รับออเดอร์แล้ว',
    deliveredStatus: 'จัดส่งแล้ว', confirmedStatus: 'ยืนยันรับแล้ว', cancelledStatus: 'ยกเลิก',
    // timestamps line
    sentAt: 'ส่ง', acceptedAt: 'รับออเดอร์', deliveredAt: 'จัดส่ง', confirmedAt: 'ยืนยัน',
    // actions / forms
    quantity: 'จำนวน', quantityPh: 'เช่น 20',
    rooms: 'หมายเลขห้อง (บรรทัดละห้อง หรือคั่นด้วยจุลภาค)',
    roomsPh: '101\n102\n104: มะม่วง',
    roomsHint: 'เติม ": รายการ" หลังเลขห้องเพื่อระบุของเฉพาะห้อง เช่น "104: มะม่วง"',
    notePh: 'หมายเหตุ (ไม่บังคับ)',
    sendOrder: 'ส่งออเดอร์', acceptOrder: 'รับออเดอร์', markDelivered: 'บันทึกว่าจัดส่งแล้ว',
    confirmReceived: 'ยืนยันการรับ', cancelOrder: 'ยกเลิก',
    confirmCancelOrder: 'ยกเลิกออเดอร์นี้?',
    roomChecklist: 'เช็คลิสต์รายห้อง',
    roomsDone: (d: number, t: number) => `${d}/${t} ห้อง`,
    quantityRequired: 'กรุณาระบุจำนวน', roomsRequired: 'กรุณาเพิ่มอย่างน้อยหนึ่งห้อง',
    orderSent: 'ส่งออเดอร์แล้ว', orderAccepted: 'รับออเดอร์แล้ว', orderDelivered: 'บันทึกการจัดส่งแล้ว',
    orderConfirmed: 'ยืนยันการรับแล้ว', orderCancelled: 'ยกเลิกออเดอร์แล้ว',
    // templates view
    addTemplate: 'เพิ่มแม่แบบ', editTemplate: 'แก้ไขแม่แบบ', newTemplate: 'แม่แบบใหม่',
    name: 'ชื่อ (อังกฤษ)', namePh: 'เช่น Welcome drinks', nameTh: 'ชื่อ (ไทย ไม่บังคับ)',
    requestDept: 'แผนกผู้สั่ง', fulfillDept: 'แผนกผู้จัดส่ง',
    orderType: 'ประเภทออเดอร์', bulk: 'รวม (จัดส่งครั้งเดียว)', perRoom: 'รายห้อง (เช็คลิสต์ห้อง)',
    bulkShort: 'รวม', perRoomShort: 'รายห้อง',
    dueTime: 'เวลากำหนดส่ง', defaultItem: 'รายการเริ่มต้น', defaultItemPh: 'เช่น จานผลไม้',
    itemByWeekday: 'รายการแตกต่างตามวันในสัปดาห์',
    mon: 'จ.', tue: 'อ.', wed: 'พ.', thu: 'พฤ.', fri: 'ศ.', sat: 'ส.', sun: 'อา.',
    activeLabel: 'เปิดใช้งาน (แสดงในเมนูสั่งของ)', inactiveBadge: 'ปิดใช้งาน',
    save: 'บันทึก', cancel: 'ยกเลิก', delete: 'ลบ',
    nameRequired: 'กรุณากรอกชื่อแม่แบบ',
    sameDeptError: 'แผนกผู้สั่งและแผนกผู้จัดส่งต้องไม่ใช่แผนกเดียวกัน',
    confirmDeleteTemplate: 'ลบแม่แบบนี้? ออเดอร์ที่ผ่านมาจะยังคงอยู่',
    templateSaved: 'บันทึกแม่แบบแล้ว', templateAdded: 'เพิ่มแม่แบบแล้ว', templateDeleted: 'ลบแม่แบบแล้ว',
    // report
    reportTab: 'สร้างรายงาน', reportTitle: 'รายงานงานประจำวัน',
    reportDaily: 'รายวัน', reportWeekly: 'รายสัปดาห์', reportPeriod: 'ช่วงเวลา',
    reportPrint: 'พิมพ์ / บันทึก PDF', reportNoData: 'ไม่มีรายการในช่วงเวลานี้',
    reportDate: 'วันที่', reportRoutine: 'งานประจำ', reportItem: 'รายการ', reportQty: 'จำนวน',
    reportRooms: 'ห้อง', reportFrom: 'แผนกผู้ขอ', reportTo: 'แผนกผู้จัดทำ', reportStatus: 'สถานะ',
    reportSummary: 'สรุปตามรายการ', reportTotal: 'รวม',
    reportGeneratedBy: 'จัดทำโดย', reportGeneratedAt: 'สร้างเมื่อ', reportForAccounting: 'สำหรับบันทึกของฝ่ายบัญชี',
    reportVariants: 'ตัวเลือก', reportTotalRooms: (n: number) => `${n} ห้อง`,
    // ── order-ahead scheduling ──
    tomorrowBtn: 'พรุ่งนี้',
    orderByOn: (close: string, day: string) => `สั่งภายใน ${close} ${day}`,
    readyByOn: (due: string, day: string) => `ต้องการก่อน ${due} ${day}`,
    today: 'วันนี้', tomorrow: 'พรุ่งนี้',
    windowPassed: 'เลยเวลาสั่งแล้ว',
    lateTag: 'ล่าช้า',
    toPlaceForTomorrow: (n: number) => `มี ${n} รายการที่ต้องสั่งสำหรับพรุ่งนี้`,
    toPlaceForDate: (n: number, day: string) => `มี ${n} รายการที่ต้องสั่งสำหรับ${day}`,
    // ── bulk unit ──
    quantityUnit: (unit: string) => `จำนวน (${unit})`,
    // ── per-room variants ──
    pickRooms: 'เลือกห้อง', tapToAssign: 'แตะห้องเพื่อเพิ่ม แตะอีกครั้งเพื่อเปลี่ยนตัวเลือก',
    roomGridSummary: (parts: string, total: number) => `${parts} · ${total} ห้อง`,
    noVariantRooms: 'กรุณาเลือกอย่างน้อยหนึ่งห้อง',
    clearRooms: 'ล้าง',
    variantFor: (room: string) => `ตัวเลือกสำหรับ ${room}`,
    // ── PIC ──
    personInCharge: 'ผู้รับผิดชอบ',
    picWholeDept: 'ทั้งแผนก', picSpecificPeople: 'ระบุบุคคล',
    picNoneSelected: 'กรุณาเลือกอย่างน้อยหนึ่งคน',
    picSelectPeople: 'เลือกบุคคล',
    // ── timeline ──
    timeline: 'ไทม์ไลน์', timelineEmpty: 'ยังไม่มีเหตุการณ์',
    evSent: 'ส่งออเดอร์', evAccepted: 'รับออเดอร์', evDelivered: 'บันทึกการจัดส่ง',
    evConfirmed: 'ยืนยันการรับ', evCancelled: 'ยกเลิก', evRoomDelivered: 'จัดส่งแล้ว',
    evPicChanged: 'เปลี่ยนผู้รับผิดชอบ',
    someone: 'บางคน',
    // ── mute ──
    muteRoutine: 'ปิดการแจ้งเตือนงานนี้ (เฉพาะฉัน)',
    unmuteRoutine: 'เปิดการแจ้งเตือนงานนี้',
    muted: 'ปิดเสียงแล้ว', muteToggleFailed: 'ไม่สามารถอัปเดตการปิดเสียงได้',
    // ── template editor (new) ──
    perRoomVariants: 'รายห้องพร้อมตัวเลือก', perRoomVariantsShort: 'ตัวเลือก',
    unitLabel: 'หน่วย (แบบรวม)', unitLabelPh: 'เช่น แกลลอน',
    variantsEditor: 'ตัวเลือก', addVariant: 'เพิ่มตัวเลือก',
    variantCode: 'รหัส', variantLabel: 'ป้ายชื่อ (อังกฤษ)', variantLabelTh: 'ป้ายชื่อ (ไทย)',
    variantsRequired: 'กรุณาเพิ่มอย่างน้อยหนึ่งตัวเลือกสำหรับประเภทนี้',
    orderOpen: 'เปิดให้สั่งเวลา', orderClose: 'ปิดรับสั่งเวลา',
    remindAt: 'เวลาเตือน (ไม่บังคับ)',
  },
  roles: {
    super_admin: 'ผู้ดูแลระบบ', manager: 'ผู้จัดการ', staff: 'พนักงาน',
  },
  common: {
    loading: 'กำลังโหลด...', back: 'กลับ',
    mobileView: 'มุมมองมือถือ', desktopView: 'มุมมองเดสก์ท็อป',
    switchToDesktop: 'สลับเป็นมุมมองเดสก์ท็อป', switchToMobile: 'สลับเป็นมุมมองมือถือ',
    language: 'ไทย',
  },
}

interface LangContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: Translations
}

const LangContext = createContext<LangContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem('kaizen-lang') as Lang) || 'en'
  )
  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('kaizen-lang', l)
    // Best-effort: persist to the profile so server-side push notifications can be
    // localized to this recipient. No-op (RLS) when signed out, e.g. on the Login screen.
    supabase.auth.getUser().then(({ data }) => {
      const uid = data.user?.id
      if (uid) supabase.from('kaizen_profiles').update({ preferred_lang: l }).eq('id', uid)
    }).catch(() => {})
  }
  // On sign-in, reconcile language with the profile: adopt the user's saved preference
  // (so it follows them across devices), or seed it from the current device when unset
  // (so server-side push notifications have a language to localize to).
  useEffect(() => {
    let active = true
    async function sync() {
      const { data } = await supabase.auth.getUser()
      const uid = data.user?.id
      if (!uid || !active) return
      const { data: prof } = await supabase.from('kaizen_profiles').select('preferred_lang').eq('id', uid).maybeSingle()
      const saved = (prof as { preferred_lang?: string } | null)?.preferred_lang
      if (saved === 'th' || saved === 'en') {
        if (active) { setLangState(saved); localStorage.setItem('kaizen-lang', saved) }
      } else {
        supabase.from('kaizen_profiles').update({ preferred_lang: localStorage.getItem('kaizen-lang') || 'en' }).eq('id', uid)
      }
    }
    sync()
    const { data: sub } = supabase.auth.onAuthStateChange((evt) => { if (evt === 'SIGNED_IN') sync() })
    return () => { active = false; sub.subscription.unsubscribe() }
  }, [])

  const t = lang === 'th' ? th : en
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
