import React, { createContext, useContext, useState } from 'react'

export type Lang = 'en' | 'th'

const en = {
  nav: {
    dashboard: 'Dashboard', cases: 'Cases', newCase: 'New Case',
    calendar: 'Calendar', performance: 'Performance',
    maintenance: 'Preventive Maintenance',
    notifications: 'Notifications', users: 'Users', settings: 'Settings',
    signOut: 'Sign Out', home: 'Home', alerts: 'Alerts',
  },
  login: {
    title: 'Sign In', signInAs: 'Sign in as', superAdmin: 'Super Admin',
    manager: 'Manager', staff: 'Staff', department: 'Department',
    selectDept: 'Select your department', username: 'Username',
    email: 'Email Address', password: 'Password',
    enterUsername: 'Enter your username', enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    footer: 'Kaizen System · Internal Use Only',
    noDeptError: 'Please select your department.',
    companyCode: 'Company Code',
    enterCompanyCode: 'Your company code',
    noCompanyCode: 'Please enter your company code.',
    forgotPassword: 'Forgot password?',
    backToLogin: 'Back to Sign In',
    resetTitle: 'Reset Password',
    resetSubtitle: 'Enter your email and we\'ll send you a reset link.',
    sendResetLink: 'Send Reset Link',
    resetSent: 'Check your email for a password reset link.',
    contactManager: 'Contact your manager or HR to reset your password.',
    emailNotRegistered: "We couldn't find an account with this email. Please reach out to your system admin or HR department.",
  },
  dashboard: {
    title: 'Dashboard', welcome: 'Welcome back',
    totalCases: 'Total Cases', open: 'Open', inProgress: 'In Progress',
    resolved: 'Resolved', waitingApproval: 'Waiting Approval',
    caseOverview: 'Case Overview', casesShort: 'Cases', totalShort: 'Total',
    monthlyCases: 'Monthly Cases',
    criticalBanner: (n: number) => `${n} critical ${n === 1 ? 'case requires' : 'cases require'} immediate attention.`,
    slaBanner: (n: number) => `${n} case${n === 1 ? '' : 's'} overdue.`,
    view: 'View', recentCases: 'Recent Cases', viewAll: 'View all',
    noCases: 'No cases yet', casesByDept: 'Cases by Department',
    noData: 'No data', newCase: 'New Case',
    avgResolution: 'Avg Resolution', resolutionRate: 'Resolution Rate',
    casesThisMonth: 'Cases This Month', overdueSLA: 'Overdue',
    recurringIssues: 'Recurring Issues',
    deptPerformance: 'Department Performance',
    openCases: 'Open Cases', avgDays: 'Avg Days', overdue: 'Overdue',
    casesByCategory: 'Cases by Category',
  },
  cases: {
    title: 'Cases', newCase: 'New Case',
    search: 'Search by title, case number...', allStatuses: 'All Statuses',
    allPriorities: 'All Priorities', noFound: 'No cases found',
    adjustFilters: 'Try adjusting your filters or create a new case',
    caseNo: 'Case #', titleCol: 'Title', dept: 'Department',
    priority: 'Priority', status: 'Status', age: 'Age', duration: 'Duration',
    export: 'Export', due: 'Due',
    caseCount: (n: number) => `${n} ${n === 1 ? 'case' : 'cases'}`,
    allCategories: 'All Categories', slaBreached: 'Overdue',
    category: 'Category',
  },
  createCase: {
    title: 'Report a Problem', subtitle: 'Document the issue so it can be tracked and resolved',
    caseDetails: 'Case Details', department: 'Department',
    problemTitle: 'Problem Title', problemPlaceholder: 'e.g. Broken chair in dining area, Table 5',
    description: 'Description', descPlaceholder: 'Describe the problem in detail. Include location, severity, and any relevant context...',
    priority: 'Priority', photoEvidence: 'Photo Evidence',
    photoSubtitle: 'Upload photos of the problem to help the team understand the issue.',
    submit: 'Submit Case', cancel: 'Cancel',
    fillRequired: 'Please fill in all required fields.',
    created: (n: string) => `Case ${n} created successfully!`,
    failed: 'Failed to create case. Please try again.',
    dueDate: 'Due Date', optional: '(optional)', addPhotos: 'Add Photos',
    category: 'Category', selectCategory: 'Select category',
    recurring: 'Recurring Problem', recurringHint: 'Check if this issue has happened before',
  },
  status: {
    open: 'Open', assigned: 'Assigned', in_progress: 'In Progress',
    pending_manager_approval: 'Pending Approval',
    pending_admin_approval: 'Pending Approval',
    closed: 'Closed', reopened: 'Reopened',
  },
  priority: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
  users: {
    title: 'Users', addUser: 'Add User', accounts: 'accounts',
    superAdmins: 'Super Admins', managers: 'Managers', staff: 'Staff',
    createTitle: 'Create New User', createSubtitle: 'Add a new staff, manager, or admin account.',
    fullName: 'Full Name', fullNamePlaceholder: 'e.g. Somchai Kaewkham',
    username: 'Username', emailAddress: 'Email Address',
    emailPlaceholder: 'e.g. name@nanirand.com', password: 'Password',
    minPassword: 'Min. 6 characters', createAccount: 'Create Account', cancel: 'Cancel',
    inactive: '(Inactive)', noYet: (label: string) => `No ${label.toLowerCase()} yet`,
    confirmDeactivate: (active: boolean) => `Are you sure you want to ${active ? 'deactivate' : 'reactivate'} this account?`,
    confirmDelete: (name: string) => `Permanently delete ${name}'s account? This cannot be undone.`,
    deactivated: 'Account deactivated.', reactivated: 'Account reactivated.', deleted: 'Account deleted.',
    created: 'Account created successfully.', failedCreate: 'Failed to create user.',
    failedStatus: 'Failed to update account status.', failedDelete: 'Failed to delete account.',
    fillRequired: 'Full name and password are required.',
    usernameRequired: 'Username is required for staff accounts.',
    emailRequired: 'Email is required for manager and admin accounts.',
    minPwd: 'Password must be at least 6 characters.',
    dept: 'Department', roleLabel: 'Role',
    editTitle: 'Edit User', editSubtitle: 'Update user details or reset their password.',
    resetPassword: 'Reset Password', keepCurrent: '(leave blank to keep current)',
    saveChanges: 'Save Changes',
  },
  notifications: {
    title: 'Notifications', markAllRead: 'Mark all read',
    noNotifications: 'No notifications', viewAll: 'View all notifications',
    allTab: 'All', unreadTab: 'Unread', allRead: 'All notifications marked as read.',
    empty: "You're all caught up!",
    today: 'Today', yesterday: 'Yesterday', thisWeek: 'This Week', older: 'Older',
  },
  settings: {
    title: 'Settings', theme: 'Color Theme', themeSubtitle: "Customize the app's color scheme",
    presets: 'Presets', primaryColor: 'Primary Color', accentColor: 'Accent Color',
    sidebarColor: 'Sidebar Color', applyTheme: 'Apply Theme', applying: 'Applying...',
    themeApplied: 'Theme updated successfully!', failedTheme: 'Failed to update theme.',
    adminOnly: 'Theme settings can only be changed by Super Admin.',
    changePassword: 'Change Password', passwordSubtitle: 'Update your login password',
    currentPassword: 'Current Password', newPassword: 'New Password',
    confirmPassword: 'Confirm New Password', updatePassword: 'Update Password',
    updating: 'Updating...', passwordUpdated: 'Password updated successfully!',
    failedPassword: 'Failed to update password.', mismatch: 'New passwords do not match.',
    accountInfo: 'Account Information', name: 'Name', role: 'Role', dept: 'Department',
  },
  caseDetail: {
    caseInfo: 'Case Information', createdBy: 'Created by', reportedOn: 'Reported on',
    translate: 'Translate', showOriginal: 'Show original',
    machineTranslation: 'Machine translation', translateFailed: 'Translation unavailable — please try again.',
    recurringChronic: (n: number) => `Chronic Issue · ${n} reports`,
    recurringRecurring: (n: number) => `Recurring Issue · ${n} reports`,
    recurringOnce: (n: number) => `Reported Before · ${n} report`,
    recurringChronicAdvice: 'This location has been reported 3+ times. Consider a permanent fix or replacement.',
    recurringRecurringAdvice: 'This location has been reported multiple times. Monitor closely.',
    recurringOnceAdvice: 'This location was reported once before.',
    openedBy: 'Opened by:', inCharge: 'In Charge:', dueLabel: 'Due:',
    removedFromCompany: 'No longer with the company',
    addDueDate: '+ Add due date', noDueDate: 'No due date', notifyAll: 'Notify all',
    lastUpdated: 'Last updated', duration: 'Duration',
    proposedSolution: 'Proposed Solution', assignedDepts: 'Departments Involved',
    timeline: 'Timeline', problemPhotos: 'Problem Photos', resolutionPhotos: 'Resolution Photos',
    noPhotos: 'No photos',
    assignDepts: 'Assign Departments', proposeSolution: 'Propose Solution',
    solutionPlaceholder: 'Describe the proposed solution...',
    assignBtn: 'Submit',
    resolveCase: 'Resolve Case', resolutionDesc: 'Resolution Description',
    resolutionPlaceholder: 'Describe how the problem was resolved...',
    uploadEvidence: 'Upload Evidence Photos', submitResolution: 'Submit Resolution',
    approveTitle: 'Approve Resolution', approveDesc: 'Approve and notify Top Management for final review and closure.',
    approveBtn: 'Approve Resolution',
    closeTitle: 'Close Case', closeDesc: 'Confirm the resolution is satisfactory and close this case.', closeBtn: 'Close Case',
    reopenTitle: 'Reopen Case', reopenDesc: 'Reopen this case if the issue was not fully resolved.', reopenBtn: 'Reopen Case',
    deleteTitle: 'Delete Case', deleteDesc: 'Permanently delete this case and all associated data.', deleteBtn: 'Delete Case',
    confirmClose: 'Close this case? This marks it as fully resolved.',
    confirmReopen: 'Reopen this case?',
    confirmDelete: 'Permanently delete this case? This cannot be undone.',
    selectDepts: 'Select at least one department.',
    provideSolution: 'Please provide a proposed solution.',
    provideResolution: 'Please provide a resolution description.',
    notFound: 'Case not found.',
    changePriority: 'Change Priority',
    changePriorityBtn: 'Update Priority',
    priorityChanged: (p: string) => `Priority changed to ${p}.`,
    priorityChangedNotif: (n: string, p: string) => `Case ${n} priority has been changed to ${p} by Super Admin.`,
    editCase: 'Edit Case', assignedTo: 'Assigned to:',
    internalNotes: 'Internal Notes', noNotes: 'No notes yet. Add one below.',
    notePlaceholder: 'Add an internal note...',
    mentionHint: 'Type @ to mention and notify a teammate.',
    postNote: 'Post', noteCount: (n: number) => `${n} note${n !== 1 ? 's' : ''}`,
    noActivity: 'No activity yet',
    openFor: 'Open for', dueDateLabel: 'Due date', daysLeftLabel: 'Days left',
    notSet: 'Not set', dueToday: 'Due Today',
    overdueBy: (n: number) => `Overdue by ${n} day${n !== 1 ? 's' : ''}`,
    daysLeftCount: (n: number) => `${n} day${n !== 1 ? 's' : ''} left`,
    currentPriority: 'Current:',
    editModalTitle: 'Edit Case', fieldTitle: 'Title', fieldDescription: 'Description',
    fieldDueDate: 'Due Date', fieldStatus: 'Status',
    statusManualNote: 'Changing status manually will be recorded in the timeline.',
    saveChanges: 'Save Changes', cancelBtn: 'Cancel',
    assignStaff: 'Assign staff', selectNewPriority: 'Select new priority',
    selectDept: 'Select department', selectStatus: 'Select status',
    noStaffAssigned: 'No staff assigned',
    addDept: 'Add department...', addDeptBtn: 'Add',
    recurringBadge: 'Recurring Issue', printPdf: 'Print / PDF',
    relatedCases: 'Related Cases', linkCase: 'Link a case...', noRelatedCases: 'No related cases',
    unlinkCase: 'Unlink',
  },
  categories: {
    maintenance: 'Maintenance', cleanliness: 'Cleanliness', safety: 'Safety',
    guest_complaint: 'Guest Complaint', equipment: 'Equipment', other: 'Other',
  },
  perf: {
    overallTitle: 'Overall Performance Score',
    staffCard: 'Staff scorecard', leadershipCard: 'Leadership scorecard',
    tapHint: 'tap an indicator to see how it’s measured',
    scoreOutOf: 'Score out of 100', weight: 'Weight',
    closed: 'closed', overdue: 'overdue', reopened: 'reopened', avg: 'avg',
    activeDays: 'active days', activeDay: 'active day', actions: 'actions',
    noApprovals: 'no approvals yet', noClosed: 'no closed cases',
    resolutionRate: 'Resolution Rate',
    resolutionRateInfo: 'The share of cases you’re responsible for (reported or In Charge) that you’ve resolved and closed.',
    onTime: 'On-Time Delivery',
    onTimeInfo: 'The share of your cases that are NOT past their due date — how reliably you deliver on time.',
    speed: 'Resolution Speed',
    speedInfo: 'How fast you resolve cases on average, scored against a 48-hour target. Resolving within 48h scores full marks.',
    quality: 'Quality',
    qualityInfo: 'How well your fixes hold up — the share of your resolved cases that did NOT get reopened. Fewer reopens = higher quality.',
    engagement: 'Engagement',
    engagementInfo: 'How actively you engage with Kaizen — your active days over the last 30 days plus in-system actions (updates, comments, resolutions). Measured over a month, so one missed login barely affects it.',
    approval: 'Approval Responsiveness',
    approvalInfo: 'How quickly you approve cases your team submits — the average time from a staff resolution to your approval (target: within 24h). Faster unblocking scores higher.',
    teamRes: 'Team Resolution Rate',
    teamResInfo: 'The share of your department’s cases that have been resolved and closed — your team’s overall output.',
    teamSla: 'Team SLA Health',
    teamSlaInfo: 'The share of your department’s cases that are NOT overdue — how well you keep the team on schedule.',
    leadership: 'Leadership & Quality',
    leadershipInfo: 'A blend of work quality (few cases reopened) and backlog control (few cases overdue) across your department — how healthy your team’s pipeline is.',
    oversight: 'Oversight Engagement',
    oversightInfo: 'How actively you use Kaizen to manage — your active days over the last 30 days combined with in-system actions (assignments, approvals, comments). A missed day barely moves it; consistent absence lowers it.',
  },
  calendar: {
    allDepts: 'All Departments', filterByDept: 'Filter by department',
    today: 'Today', more: 'more', priorityLabel: 'Priority:',
    casesCalendar: 'Cases Calendar',
    combined: 'Combined', casePriority: 'Case Priority:', pmStatus: 'PM Status:',
    noMaintenance: 'No maintenance scheduled.', nothingDay: 'Nothing on this day.',
  },
  pm: {
    scheduler: 'Preventive Maintenance Scheduler', open: 'Open',
    addAsset: 'Add Asset', searchAssets: 'Search assets…',
    noAssets: 'No assets registered yet.', noAssetsFiltered: 'No assets match your filter.',
    registerFirst: '+ Register your first asset', next: 'Next',
    good: 'Up to date', dueSoon: 'Due soon', overdue: 'Overdue', notScheduled: 'Not scheduled', inactiveStatus: 'Inactive',
    scheduled: 'Scheduled', inProgress: 'In progress', awaitingApproval: 'Awaiting approval', done: 'Done',
    editAsset: 'Edit Asset', registerAsset: 'Register Asset',
    assetName: 'Asset name / tag', assetNamePh: 'e.g. Lobby Split A/C #1',
    equipmentType: 'Equipment type', selectType: '— select —',
    location: 'Location / zone', locationPh: 'Building / floor / room',
    serialNo: 'Serial no.', model: 'Model',
    responsibleDept: 'Responsible department', none: '— none —',
    frequency: 'Frequency', customEvery: 'Custom (every N days)', everyNDays: 'Every N days',
    estMinutes: 'Est. minutes', optional: 'optional',
    lastMaint: 'Last maintenance', nextMaint: 'Next maintenance',
    checklist: 'Maintenance checklist (one item per line)',
    checklistPh: 'Clean / replace filters\nCheck refrigerant\nTest thermostat',
    notesInstr: 'Notes / instructions', activeInclude: 'Active (include in scheduling)',
    save: 'Save', register: 'Register', cancel: 'Cancel', delete: 'Delete',
    assetNameRequired: 'Asset name is required.', assetSaved: 'Asset updated', assetAdded: 'Asset added',
    confirmDeleteAsset: 'Delete this asset? Its maintenance history will be removed.',
    checklistTitle: 'Checklist', pass: 'PASS', fail: 'FAIL', na: 'NA',
    readings: 'Readings', parts: 'Parts', findings: 'Findings', performed: 'Performed',
    readingsLabel: 'Readings / measurements', readingsPh: 'e.g. 12°C, 220V',
    partsLabel: 'Parts / consumables used', findingsLabel: 'Findings / notes',
    start: 'Start', complete: 'Complete', approve: 'Approve', return: 'Return',
    rejectPrompt: 'Reason for returning this task to the technician?',
    recorded: 'Maintenance recorded', approvedToast: 'Maintenance approved', returnedToast: 'Returned to technician',
    awaitingNote: 'Awaiting approval', awaitingBy: 'by the responsible manager / Top Management',
    compliance: 'Compliance', dueThisWeek: 'Due this week', doneThisMonth: 'Done this month', onTimeRate: 'On-time rate',
    setupScheduler: 'Set up the scheduler →',
    settingsTitle: 'Preventive Maintenance — Settings',
    settingsDesc: 'Approval, reminder and escalation rules for maintenance tasks.',
    requireApproval: 'Require approval for maintenance tasks',
    requireApprovalDesc: 'When on, a completed task waits for the responsible department manager (or Top Management) to approve before the cycle advances.',
    dueSoonWindow: '"Due soon" window (days)',
    dueSoonWindowDesc: 'Assets turn amber within this many days of their next service.',
    escalateAfter: 'Escalate to a Case after (days overdue)',
    escalateAfterDesc: 'A missed task this many days overdue auto-creates a Case.',
    autoEscalate: 'Auto-escalate overdue maintenance to a Case',
    autoEscalateDesc: "Creates a normal Case (priority High) so an overdue task can't be forgotten.",
    saveSettings: 'Save settings', settingsSaved: 'Maintenance settings saved',
    typesTitle: 'Preventive Maintenance — Equipment Types',
    typesDesc: 'Define the equipment types used when registering maintenance assets. Only Top Management can edit these.',
    newType: 'New type', newTypePh: 'e.g. Heat Pump', category: 'Category', add: 'Add',
    noTypes: 'No equipment types yet.', loadDefaults: 'Load default types',
    on: 'On', off: 'Off', activate: 'Activate', deactivate: 'Deactivate', rename: 'Rename',
    defaultsAdded: 'Default equipment types added', confirmDeleteType: 'Remove equipment type',
  },
  roles: {
    super_admin: 'Super Admin', manager: 'Manager', staff: 'Staff',
  },
  common: {
    loading: 'Loading...', back: 'Back',
    mobileView: 'Mobile View', desktopView: 'Desktop View',
    switchToDesktop: 'Switch to Desktop View', switchToMobile: 'Switch to Mobile View',
    language: 'EN',
  },
} as const

// Widen the `as const` English shape: string/number literals -> primitives,
// functions preserved, nesting recursed, readonly stripped. This lets the Thai
// translation object satisfy the same structure without literal-type mismatches.
type DeepWiden<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends object
    ? { -readonly [K in keyof T]: DeepWiden<T[K]> }
    : T extends string ? string
    : T extends number ? number
    : T extends boolean ? boolean
    : T
type Translations = DeepWiden<typeof en>

const th: Translations = {
  nav: {
    dashboard: 'แดชบอร์ด', cases: 'เคส', newCase: 'รายงานใหม่',
    calendar: 'ปฏิทิน', performance: 'ประสิทธิภาพ',
    maintenance: 'การบำรุงรักษาเชิงป้องกัน',
    notifications: 'การแจ้งเตือน', users: 'ผู้ใช้งาน', settings: 'การตั้งค่า',
    signOut: 'ออกจากระบบ', home: 'หน้าหลัก', alerts: 'แจ้งเตือน',
  },
  login: {
    title: 'เข้าสู่ระบบ', signInAs: 'เข้าสู่ระบบในฐานะ', superAdmin: 'ผู้ดูแลระบบ',
    manager: 'ผู้จัดการ', staff: 'พนักงาน', department: 'แผนก',
    selectDept: 'เลือกแผนกของคุณ', username: 'ชื่อผู้ใช้',
    email: 'อีเมล', password: 'รหัสผ่าน',
    enterUsername: 'กรอกชื่อผู้ใช้', enterEmail: 'กรอกอีเมล',
    enterPassword: 'กรอกรหัสผ่าน',
    footer: 'Kaizen System · สำหรับภายในเท่านั้น',
    noDeptError: 'กรุณาเลือกแผนกของคุณ',
    companyCode: 'รหัสบริษัท',
    enterCompanyCode: 'รหัสบริษัทของคุณ',
    noCompanyCode: 'กรุณากรอกรหัสบริษัท',
    forgotPassword: 'ลืมรหัสผ่าน?',
    backToLogin: 'กลับไปเข้าสู่ระบบ',
    resetTitle: 'รีเซ็ตรหัสผ่าน',
    resetSubtitle: 'กรอกอีเมลของคุณ เราจะส่งลิงก์รีเซ็ตให้',
    sendResetLink: 'ส่งลิงก์รีเซ็ต',
    resetSent: 'กรุณาตรวจสอบอีเมลของคุณสำหรับลิงก์รีเซ็ตรหัสผ่าน',
    contactManager: 'ติดต่อผู้จัดการหรือฝ่าย HR เพื่อรีเซ็ตรหัสผ่านของคุณ',
    emailNotRegistered: 'อีเมลนี้ไม่ได้ลงทะเบียนในระบบ กรุณาติดต่อผู้ดูแลระบบหรือฝ่าย HR',
  },
  dashboard: {
    title: 'แดชบอร์ด', welcome: 'ยินดีต้อนรับกลับ',
    totalCases: 'เคสทั้งหมด', open: 'เปิดอยู่', inProgress: 'กำลังดำเนินการ',
    resolved: 'แก้ไขแล้ว', waitingApproval: 'รอการอนุมัติ',
    caseOverview: 'ภาพรวมเคส', casesShort: 'เคส', totalShort: 'ทั้งหมด',
    monthlyCases: 'เคสรายเดือน',
    criticalBanner: (n: number) => `มี ${n} เคสวิกฤตที่ต้องการการแก้ไขด่วน`,
    slaBanner: (n: number) => `${n} เคสเกินกำหนด`,
    view: 'ดู', recentCases: 'เคสล่าสุด', viewAll: 'ดูทั้งหมด',
    noCases: 'ยังไม่มีเคส', casesByDept: 'เคสตามแผนก',
    noData: 'ไม่มีข้อมูล', newCase: 'รายงานใหม่',
    avgResolution: 'เวลาแก้ไขเฉลี่ย', resolutionRate: 'อัตราการแก้ไข',
    casesThisMonth: 'เคสเดือนนี้', overdueSLA: 'เกินกำหนด',
    recurringIssues: 'ปัญหาซ้ำ',
    deptPerformance: 'ประสิทธิภาพแผนก',
    openCases: 'เคสที่เปิดอยู่', avgDays: 'เฉลี่ย (วัน)', overdue: 'เกินกำหนด',
    casesByCategory: 'เคสตามประเภท',
  },
  cases: {
    title: 'เคส', newCase: 'รายงานใหม่',
    search: 'ค้นหาด้วยชื่อหรือหมายเลขเคส...', allStatuses: 'ทุกสถานะ',
    allPriorities: 'ทุกระดับ', noFound: 'ไม่พบเคส',
    adjustFilters: 'ลองปรับตัวกรองหรือสร้างเคสใหม่',
    caseNo: 'หมายเลข', titleCol: 'ชื่อ', dept: 'แผนก',
    priority: 'ระดับ', status: 'สถานะ', age: 'อายุ', duration: 'ระยะเวลา',
    export: 'ส่งออก', due: 'กำหนดส่ง',
    caseCount: (n: number) => `${n} เคส`,
    allCategories: 'ทุกประเภท', slaBreached: 'เกินกำหนด',
    category: 'ประเภท',
  },
  createCase: {
    title: 'รายงานปัญหา', subtitle: 'บันทึกปัญหาเพื่อการติดตามและแก้ไข',
    caseDetails: 'รายละเอียดเคส', department: 'แผนก',
    problemTitle: 'ชื่อปัญหา', problemPlaceholder: 'เช่น เก้าอี้แตกในห้องอาหาร โต๊ะ 5',
    description: 'รายละเอียด', descPlaceholder: 'อธิบายปัญหาโดยละเอียด รวมถึงสถานที่ ความรุนแรง และบริบทที่เกี่ยวข้อง...',
    priority: 'ระดับความสำคัญ', photoEvidence: 'หลักฐานภาพถ่าย',
    photoSubtitle: 'อัปโหลดภาพถ่ายปัญหาเพื่อให้ทีมเข้าใจสถานการณ์',
    submit: 'ส่งเคส', cancel: 'ยกเลิก',
    fillRequired: 'กรุณากรอกข้อมูลที่จำเป็นให้ครบ',
    created: (n: string) => `สร้างเคส ${n} สำเร็จ!`,
    failed: 'ไม่สามารถสร้างเคสได้ กรุณาลองใหม่',
    dueDate: 'วันกำหนดส่ง', optional: '(ไม่บังคับ)', addPhotos: 'เพิ่มรูปภาพ',
    category: 'ประเภท', selectCategory: 'เลือกประเภท',
    recurring: 'ปัญหาที่เกิดซ้ำ', recurringHint: 'เลือกหากปัญหานี้เคยเกิดขึ้นมาก่อน',
  },
  status: {
    open: 'เปิด', assigned: 'มอบหมายแล้ว', in_progress: 'กำลังดำเนินการ',
    pending_manager_approval: 'รออนุมัติ',
    pending_admin_approval: 'รออนุมัติ',
    closed: 'ปิด', reopened: 'เปิดใหม่',
  },
  priority: { low: 'ต่ำ', medium: 'ปานกลาง', high: 'สูง', critical: 'วิกฤต' },
  users: {
    title: 'ผู้ใช้งาน', addUser: 'เพิ่มผู้ใช้', accounts: 'บัญชี',
    superAdmins: 'ผู้ดูแลระบบ', managers: 'ผู้จัดการ', staff: 'พนักงาน',
    createTitle: 'สร้างผู้ใช้ใหม่', createSubtitle: 'เพิ่มบัญชีพนักงาน ผู้จัดการ หรือผู้ดูแลระบบ',
    fullName: 'ชื่อ-นามสกุล', fullNamePlaceholder: 'เช่น สมชาย แก้วขาม',
    username: 'ชื่อผู้ใช้', emailAddress: 'อีเมล',
    emailPlaceholder: 'เช่น name@nanirand.com', password: 'รหัสผ่าน',
    minPassword: 'อย่างน้อย 6 ตัวอักษร', createAccount: 'สร้างบัญชี', cancel: 'ยกเลิก',
    inactive: '(ปิดใช้งาน)', noYet: (label: string) => `ยังไม่มี${label}`,
    confirmDeactivate: (active: boolean) => `ต้องการ${active ? 'ปิดใช้งาน' : 'เปิดใช้งาน'}บัญชีนี้?`,
    confirmDelete: (name: string) => `ลบบัญชีของ ${name} ถาวร? ไม่สามารถกู้คืนได้`,
    deactivated: 'ปิดใช้งานบัญชีแล้ว', reactivated: 'เปิดใช้งานบัญชีแล้ว', deleted: 'ลบบัญชีแล้ว',
    created: 'สร้างบัญชีสำเร็จ', failedCreate: 'ไม่สามารถสร้างผู้ใช้ได้',
    failedStatus: 'ไม่สามารถอัปเดตสถานะบัญชีได้', failedDelete: 'ไม่สามารถลบบัญชีได้',
    fillRequired: 'กรุณากรอกชื่อและรหัสผ่าน',
    usernameRequired: 'กรุณากรอกชื่อผู้ใช้สำหรับพนักงาน',
    emailRequired: 'กรุณากรอกอีเมลสำหรับผู้จัดการและผู้ดูแลระบบ',
    minPwd: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    dept: 'แผนก', roleLabel: 'บทบาท',
    editTitle: 'แก้ไขผู้ใช้', editSubtitle: 'อัปเดตข้อมูลผู้ใช้หรือรีเซ็ตรหัสผ่าน',
    resetPassword: 'รีเซ็ตรหัสผ่าน', keepCurrent: '(เว้นว่างเพื่อคงรหัสผ่านเดิม)',
    saveChanges: 'บันทึกการเปลี่ยนแปลง',
  },
  notifications: {
    title: 'การแจ้งเตือน', markAllRead: 'ทำเครื่องหมายอ่านทั้งหมด',
    noNotifications: 'ไม่มีการแจ้งเตือน', viewAll: 'ดูการแจ้งเตือนทั้งหมด',
    allTab: 'ทั้งหมด', unreadTab: 'ยังไม่อ่าน', allRead: 'ทำเครื่องหมายอ่านทั้งหมดแล้ว',
    empty: 'คุณอ่านทุกอย่างแล้ว!',
    today: 'วันนี้', yesterday: 'เมื่อวาน', thisWeek: 'สัปดาห์นี้', older: 'เก่ากว่า',
  },
  settings: {
    title: 'การตั้งค่า', theme: 'ธีมสี', themeSubtitle: 'ปรับแต่งรูปแบบสีของแอป',
    presets: 'รูปแบบสำเร็จรูป', primaryColor: 'สีหลัก', accentColor: 'สีเน้น',
    sidebarColor: 'สีแถบเมนู', applyTheme: 'ใช้ธีม', applying: 'กำลังใช้งาน...',
    themeApplied: 'อัปเดตธีมสำเร็จ!', failedTheme: 'ไม่สามารถอัปเดตธีมได้',
    adminOnly: 'การตั้งค่าธีมสามารถเปลี่ยนได้โดยผู้ดูแลระบบเท่านั้น',
    changePassword: 'เปลี่ยนรหัสผ่าน', passwordSubtitle: 'อัปเดตรหัสผ่านเข้าสู่ระบบของคุณ',
    currentPassword: 'รหัสผ่านปัจจุบัน', newPassword: 'รหัสผ่านใหม่',
    confirmPassword: 'ยืนยันรหัสผ่านใหม่', updatePassword: 'อัปเดตรหัสผ่าน',
    updating: 'กำลังอัปเดต...', passwordUpdated: 'อัปเดตรหัสผ่านสำเร็จ!',
    failedPassword: 'ไม่สามารถอัปเดตรหัสผ่านได้', mismatch: 'รหัสผ่านใหม่ไม่ตรงกัน',
    accountInfo: 'ข้อมูลบัญชี', name: 'ชื่อ', role: 'บทบาท', dept: 'แผนก',
  },
  caseDetail: {
    caseInfo: 'ข้อมูลเคส', createdBy: 'สร้างโดย', reportedOn: 'รายงานเมื่อ',
    translate: 'แปล', showOriginal: 'ดูต้นฉบับ',
    machineTranslation: 'แปลด้วยเครื่อง', translateFailed: 'แปลไม่สำเร็จ — กรุณาลองใหม่',
    recurringChronic: (n: number) => `ปัญหาเรื้อรัง · ${n} รายงาน`,
    recurringRecurring: (n: number) => `ปัญหาเกิดซ้ำ · ${n} รายงาน`,
    recurringOnce: (n: number) => `เคยรายงานแล้ว · ${n} รายงาน`,
    recurringChronicAdvice: 'สถานที่นี้ถูกรายงานมากกว่า 3 ครั้ง ควรพิจารณาแก้ไขถาวรหรือเปลี่ยนใหม่',
    recurringRecurringAdvice: 'สถานที่นี้ถูกรายงานหลายครั้ง ควรติดตามอย่างใกล้ชิด',
    recurringOnceAdvice: 'สถานที่นี้เคยถูกรายงานมาก่อนหนึ่งครั้ง',
    openedBy: 'เปิดโดย:', inCharge: 'ผู้รับผิดชอบ:', dueLabel: 'กำหนดเสร็จ:',
    removedFromCompany: 'ไม่ได้อยู่กับบริษัทแล้ว',
    addDueDate: '+ เพิ่มกำหนดเสร็จ', noDueDate: 'ไม่มีกำหนดเสร็จ', notifyAll: 'แจ้งทั้งหมด',
    lastUpdated: 'อัปเดตล่าสุด', duration: 'ระยะเวลา',
    proposedSolution: 'แนวทางแก้ไขที่เสนอ', assignedDepts: 'แผนกที่เกี่ยวข้อง',
    timeline: 'ไทม์ไลน์', problemPhotos: 'ภาพถ่ายปัญหา', resolutionPhotos: 'ภาพถ่ายการแก้ไข',
    noPhotos: 'ไม่มีภาพถ่าย',
    assignDepts: 'มอบหมายแผนก', proposeSolution: 'เสนอแนวทางแก้ไข',
    solutionPlaceholder: 'อธิบายแนวทางแก้ไขที่เสนอ...',
    assignBtn: 'ยืนยัน',
    resolveCase: 'แก้ไขเคส', resolutionDesc: 'รายละเอียดการแก้ไข',
    resolutionPlaceholder: 'อธิบายวิธีการแก้ไขปัญหา...',
    uploadEvidence: 'อัปโหลดภาพถ่ายหลักฐาน', submitResolution: 'ส่งการแก้ไข',
    approveTitle: 'อนุมัติการแก้ไข', approveDesc: 'อนุมัติและส่งต่อให้ผู้ดูแลระบบปิดเคส',
    approveBtn: 'อนุมัติการแก้ไข',
    closeTitle: 'ปิดเคส', closeDesc: 'ปิดเคสนี้หลังจากตรวจสอบการแก้ไขแล้ว', closeBtn: 'ปิดเคส',
    reopenTitle: 'เปิดเคสใหม่', reopenDesc: 'เปิดเคสใหม่หากปัญหายังไม่ได้รับการแก้ไขอย่างสมบูรณ์', reopenBtn: 'เปิดเคสใหม่',
    deleteTitle: 'ลบเคส', deleteDesc: 'ลบเคสนี้และข้อมูลทั้งหมดที่เกี่ยวข้องถาวร', deleteBtn: 'ลบเคส',
    confirmClose: 'ปิดเคสนี้? จะถือว่าแก้ไขเสร็จสมบูรณ์',
    confirmReopen: 'เปิดเคสนี้ใหม่?',
    confirmDelete: 'ลบเคสนี้ถาวร? ไม่สามารถกู้คืนได้',
    selectDepts: 'กรุณาเลือกอย่างน้อยหนึ่งแผนก',
    provideSolution: 'กรุณาระบุแนวทางแก้ไขที่เสนอ',
    provideResolution: 'กรุณาระบุรายละเอียดการแก้ไข',
    notFound: 'ไม่พบเคส',
    changePriority: 'เปลี่ยนระดับความสำคัญ',
    changePriorityBtn: 'อัปเดตระดับความสำคัญ',
    priorityChanged: (p: string) => `เปลี่ยนระดับความสำคัญเป็น ${p} แล้ว`,
    priorityChangedNotif: (n: string, p: string) => `ระดับความสำคัญของเคส ${n} ถูกเปลี่ยนเป็น ${p} โดยผู้ดูแลระบบ`,
    editCase: 'แก้ไขเคส', assignedTo: 'มอบหมายให้:',
    internalNotes: 'บันทึกภายใน', noNotes: 'ยังไม่มีบันทึก เพิ่มด้านล่าง',
    notePlaceholder: 'เพิ่มบันทึกภายใน...',
    mentionHint: 'พิมพ์ @ เพื่อกล่าวถึงและแจ้งเตือนเพื่อนร่วมงาน',
    postNote: 'บันทึก', noteCount: (n: number) => `${n} บันทึก`,
    noActivity: 'ยังไม่มีกิจกรรม',
    openFor: 'เปิดมาแล้ว', dueDateLabel: 'กำหนดส่ง', daysLeftLabel: 'วันที่เหลือ',
    notSet: 'ไม่ได้กำหนด', dueToday: 'ครบกำหนดวันนี้',
    overdueBy: (n: number) => `เลยกำหนด ${n} วัน`,
    daysLeftCount: (n: number) => `เหลือ ${n} วัน`,
    currentPriority: 'ปัจจุบัน:',
    editModalTitle: 'แก้ไขเคส', fieldTitle: 'ชื่อเรื่อง', fieldDescription: 'รายละเอียด',
    fieldDueDate: 'วันกำหนดส่ง', fieldStatus: 'สถานะ',
    statusManualNote: 'การเปลี่ยนสถานะด้วยตนเองจะถูกบันทึกในไทม์ไลน์',
    saveChanges: 'บันทึกการเปลี่ยนแปลง', cancelBtn: 'ยกเลิก',
    assignStaff: 'มอบหมายพนักงาน', selectNewPriority: 'เลือกระดับใหม่',
    selectDept: 'เลือกแผนก', selectStatus: 'เลือกสถานะ',
    noStaffAssigned: 'ยังไม่มีพนักงานที่ได้รับมอบหมาย',
    addDept: 'เพิ่มแผนก...', addDeptBtn: 'เพิ่ม',
    recurringBadge: 'ปัญหาที่เกิดซ้ำ', printPdf: 'พิมพ์ / PDF',
    relatedCases: 'เคสที่เกี่ยวข้อง', linkCase: 'เชื่อมโยงเคส...', noRelatedCases: 'ไม่มีเคสที่เกี่ยวข้อง',
    unlinkCase: 'ยกเลิกการเชื่อมโยง',
  },
  categories: {
    maintenance: 'การซ่อมบำรุง', cleanliness: 'ความสะอาด', safety: 'ความปลอดภัย',
    guest_complaint: 'ข้อร้องเรียนแขก', equipment: 'อุปกรณ์', other: 'อื่นๆ',
  },
  perf: {
    overallTitle: 'คะแนนประสิทธิภาพโดยรวม',
    staffCard: 'เกณฑ์ประเมินพนักงาน', leadershipCard: 'เกณฑ์ประเมินภาวะผู้นำ',
    tapHint: 'แตะที่ตัวชี้วัดเพื่อดูวิธีการคำนวณ',
    scoreOutOf: 'คะแนนเต็ม 100', weight: 'น้ำหนัก',
    closed: 'ปิดแล้ว', overdue: 'เกินกำหนด', reopened: 'เปิดใหม่', avg: 'เฉลี่ย',
    activeDays: 'วันที่ใช้งาน', activeDay: 'วันที่ใช้งาน', actions: 'กิจกรรม',
    noApprovals: 'ยังไม่มีการอนุมัติ', noClosed: 'ยังไม่มีเคสที่ปิด',
    resolutionRate: 'อัตราการแก้ไข',
    resolutionRateInfo: 'สัดส่วนของเคสที่คุณรับผิดชอบ (รายงานหรือเป็นผู้รับผิดชอบ) ที่คุณแก้ไขและปิดเรียบร้อยแล้ว',
    onTime: 'ตรงตามกำหนดเวลา',
    onTimeInfo: 'สัดส่วนของเคสที่ยังไม่เกินกำหนด — สะท้อนความน่าเชื่อถือในการส่งมอบงานตรงเวลา',
    speed: 'ความเร็วในการแก้ไข',
    speedInfo: 'ความเร็วเฉลี่ยในการแก้ไขเคส วัดเทียบกับเป้าหมาย 48 ชั่วโมง หากแก้ไขภายใน 48 ชั่วโมงจะได้คะแนนเต็ม',
    quality: 'คุณภาพ',
    qualityInfo: 'การแก้ไขมีคุณภาพเพียงใด — สัดส่วนของเคสที่แก้ไขแล้วและไม่ถูกเปิดใหม่ ยิ่งเปิดใหม่น้อยยิ่งคุณภาพสูง',
    engagement: 'ความมีส่วนร่วม',
    engagementInfo: 'คุณมีส่วนร่วมกับ Kaizen มากเพียงใด — จำนวนวันที่ใช้งานใน 30 วันที่ผ่านมารวมกับกิจกรรมในระบบ (การอัปเดต ความคิดเห็น การแก้ไข) วัดตลอดทั้งเดือน การไม่เข้าระบบเพียงวันเดียวจึงแทบไม่มีผล',
    approval: 'ความรวดเร็วในการอนุมัติ',
    approvalInfo: 'คุณอนุมัติเคสที่ทีมส่งมาได้เร็วเพียงใด — เวลาเฉลี่ยจากการแก้ไขของพนักงานจนถึงการอนุมัติของคุณ (เป้าหมาย: ภายใน 24 ชั่วโมง) ยิ่งปลดล็อกงานเร็วยิ่งได้คะแนนสูง',
    teamRes: 'อัตราการแก้ไขของทีม',
    teamResInfo: 'สัดส่วนของเคสในแผนกของคุณที่แก้ไขและปิดเรียบร้อยแล้ว — ผลงานโดยรวมของทีม',
    teamSla: 'สุขภาพ SLA ของทีม',
    teamSlaInfo: 'สัดส่วนของเคสในแผนกของคุณที่ยังไม่เกินกำหนด — สะท้อนการดูแลให้ทีมทำงานตามกำหนดเวลา',
    leadership: 'ภาวะผู้นำและคุณภาพ',
    leadershipInfo: 'การผสมผสานระหว่างคุณภาพงาน (เคสถูกเปิดใหม่น้อย) และการควบคุมงานค้าง (เคสเกินกำหนดน้อย) ในแผนกของคุณ — สะท้อนความสมบูรณ์ของกระบวนการทำงานของทีม',
    oversight: 'การกำกับดูแลและการมีส่วนร่วม',
    oversightInfo: 'คุณใช้ Kaizen ในการบริหารมากเพียงใด — จำนวนวันที่ใช้งานใน 30 วันที่ผ่านมารวมกับกิจกรรมในระบบ (การมอบหมาย การอนุมัติ ความคิดเห็น) การขาดเพียงวันเดียวแทบไม่มีผล แต่การขาดหายต่อเนื่องจะทำให้คะแนนลดลง',
  },
  calendar: {
    allDepts: 'ทุกแผนก', filterByDept: 'กรองตามแผนก',
    today: 'วันนี้', more: 'เพิ่มเติม', priorityLabel: 'ระดับ:',
    casesCalendar: 'ปฏิทินเคส',
    combined: 'รวม', casePriority: 'ระดับความสำคัญเคส:', pmStatus: 'สถานะ PM:',
    noMaintenance: 'ไม่มีงานบำรุงรักษาที่กำหนดไว้', nothingDay: 'ไม่มีรายการในวันนี้',
  },
  pm: {
    scheduler: 'ระบบกำหนดการบำรุงรักษาเชิงป้องกัน', open: 'เปิด',
    addAsset: 'เพิ่มอุปกรณ์', searchAssets: 'ค้นหาอุปกรณ์…',
    noAssets: 'ยังไม่มีอุปกรณ์ที่ลงทะเบียน', noAssetsFiltered: 'ไม่มีอุปกรณ์ตรงกับตัวกรอง',
    registerFirst: '+ ลงทะเบียนอุปกรณ์ชิ้นแรก', next: 'ครั้งถัดไป',
    good: 'เป็นปัจจุบัน', dueSoon: 'ใกล้ถึงกำหนด', overdue: 'เลยกำหนด', notScheduled: 'ยังไม่กำหนด', inactiveStatus: 'ปิดใช้งาน',
    scheduled: 'กำหนดไว้', inProgress: 'กำลังดำเนินการ', awaitingApproval: 'รออนุมัติ', done: 'เสร็จสิ้น',
    editAsset: 'แก้ไขอุปกรณ์', registerAsset: 'ลงทะเบียนอุปกรณ์',
    assetName: 'ชื่อ / รหัสอุปกรณ์', assetNamePh: 'เช่น แอร์ล็อบบี้ #1',
    equipmentType: 'ประเภทอุปกรณ์', selectType: '— เลือก —',
    location: 'สถานที่ / โซน', locationPh: 'อาคาร / ชั้น / ห้อง',
    serialNo: 'หมายเลขเครื่อง', model: 'รุ่น',
    responsibleDept: 'แผนกที่รับผิดชอบ', none: '— ไม่มี —',
    frequency: 'ความถี่', customEvery: 'กำหนดเอง (ทุก N วัน)', everyNDays: 'ทุก N วัน',
    estMinutes: 'เวลาโดยประมาณ (นาที)', optional: 'ไม่บังคับ',
    lastMaint: 'บำรุงรักษาล่าสุด', nextMaint: 'บำรุงรักษาครั้งถัดไป',
    checklist: 'รายการตรวจสอบ (หนึ่งรายการต่อบรรทัด)',
    checklistPh: 'ทำความสะอาด / เปลี่ยนไส้กรอง\nตรวจสอบน้ำยา\nทดสอบเทอร์โมสตัท',
    notesInstr: 'หมายเหตุ / คำแนะนำ', activeInclude: 'ใช้งาน (รวมในการจัดตาราง)',
    save: 'บันทึก', register: 'ลงทะเบียน', cancel: 'ยกเลิก', delete: 'ลบ',
    assetNameRequired: 'กรุณาระบุชื่ออุปกรณ์', assetSaved: 'อัปเดตอุปกรณ์แล้ว', assetAdded: 'เพิ่มอุปกรณ์แล้ว',
    confirmDeleteAsset: 'ลบอุปกรณ์นี้? ประวัติการบำรุงรักษาจะถูกลบไปด้วย',
    checklistTitle: 'รายการตรวจสอบ', pass: 'ผ่าน', fail: 'ไม่ผ่าน', na: 'ไม่เกี่ยว',
    readings: 'ค่าที่อ่านได้', parts: 'อะไหล่', findings: 'สิ่งที่พบ', performed: 'ดำเนินการเมื่อ',
    readingsLabel: 'ค่าที่อ่านได้ / การวัด', readingsPh: 'เช่น 12°C, 220V',
    partsLabel: 'อะไหล่ / วัสดุสิ้นเปลืองที่ใช้', findingsLabel: 'สิ่งที่พบ / หมายเหตุ',
    start: 'เริ่ม', complete: 'เสร็จสิ้น', approve: 'อนุมัติ', return: 'ส่งกลับ',
    rejectPrompt: 'เหตุผลในการส่งงานนี้กลับให้ช่าง?',
    recorded: 'บันทึกการบำรุงรักษาแล้ว', approvedToast: 'อนุมัติการบำรุงรักษาแล้ว', returnedToast: 'ส่งกลับให้ช่างแล้ว',
    awaitingNote: 'รออนุมัติ', awaitingBy: 'โดยผู้จัดการที่รับผิดชอบ / ผู้บริหารระดับสูง',
    compliance: 'ความเป็นไปตามแผน', dueThisWeek: 'ครบกำหนดสัปดาห์นี้', doneThisMonth: 'เสร็จเดือนนี้', onTimeRate: 'อัตราตรงเวลา',
    setupScheduler: 'ตั้งค่าระบบกำหนดการ →',
    settingsTitle: 'การบำรุงรักษาเชิงป้องกัน — การตั้งค่า',
    settingsDesc: 'กฎการอนุมัติ การแจ้งเตือน และการยกระดับสำหรับงานบำรุงรักษา',
    requireApproval: 'ต้องมีการอนุมัติงานบำรุงรักษา',
    requireApprovalDesc: 'เมื่อเปิด งานที่ทำเสร็จจะรอให้ผู้จัดการแผนกที่รับผิดชอบ (หรือผู้บริหารระดับสูง) อนุมัติก่อนจึงจะเริ่มรอบถัดไป',
    dueSoonWindow: 'ช่วง "ใกล้ถึงกำหนด" (วัน)',
    dueSoonWindowDesc: 'อุปกรณ์จะเปลี่ยนเป็นสีเหลืองภายในกี่วันก่อนถึงกำหนดบำรุงรักษา',
    escalateAfter: 'ยกระดับเป็นเคสเมื่อเลยกำหนด (วัน)',
    escalateAfterDesc: 'งานที่เลยกำหนดตามจำนวนวันนี้จะสร้างเคสโดยอัตโนมัติ',
    autoEscalate: 'ยกระดับงานที่เลยกำหนดเป็นเคสอัตโนมัติ',
    autoEscalateDesc: 'สร้างเคสปกติ (ระดับสูง) เพื่อไม่ให้งานที่เลยกำหนดถูกลืม',
    saveSettings: 'บันทึกการตั้งค่า', settingsSaved: 'บันทึกการตั้งค่าการบำรุงรักษาแล้ว',
    typesTitle: 'การบำรุงรักษาเชิงป้องกัน — ประเภทอุปกรณ์',
    typesDesc: 'กำหนดประเภทอุปกรณ์ที่ใช้เมื่อลงทะเบียนอุปกรณ์ เฉพาะผู้บริหารระดับสูงเท่านั้นที่แก้ไขได้',
    newType: 'ประเภทใหม่', newTypePh: 'เช่น ปั๊มความร้อน', category: 'หมวดหมู่', add: 'เพิ่ม',
    noTypes: 'ยังไม่มีประเภทอุปกรณ์', loadDefaults: 'โหลดประเภทเริ่มต้น',
    on: 'เปิด', off: 'ปิด', activate: 'เปิดใช้งาน', deactivate: 'ปิดใช้งาน', rename: 'เปลี่ยนชื่อ',
    defaultsAdded: 'เพิ่มประเภทอุปกรณ์เริ่มต้นแล้ว', confirmDeleteType: 'ลบประเภทอุปกรณ์',
  },
  roles: {
    super_admin: 'ผู้ดูแลระบบ', manager: 'ผู้จัดการ', staff: 'พนักงาน',
  },
  common: {
    loading: 'กำลังโหลด...', back: 'กลับ',
    mobileView: 'มุมมองมือถือ', desktopView: 'มุมมองเดสก์ท็อป',
    switchToDesktop: 'สลับเป็นมุมมองเดสก์ท็อป', switchToMobile: 'สลับเป็นมุมมองมือถือ',
    language: 'ไทย',
  },
}

interface LangContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: Translations
}

const LangContext = createContext<LangContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem('kaizen-lang') as Lang) || 'en'
  )
  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('kaizen-lang', l)
  }
  const t = lang === 'th' ? th : en
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
