-- Form Generator: stores Quotations / Invoices / Tax Invoice-Receipts / Receipts
-- generated by NNR-Solutions in the System Console for its customer companies.
-- Accessed exclusively through the kaizen-console edge function (service role),
-- so RLS is enabled with no public policies (service role bypasses RLS).

CREATE TABLE IF NOT EXISTS kaizen_generated_forms (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  form_type     text NOT NULL CHECK (form_type IN ('quotation','invoice','tax_invoice_receipt','receipt')),
  doc_number    text NOT NULL,
  -- Client (the customer company this document is issued to). Snapshotted so the
  -- document never changes if the company's details are later edited.
  company_id    uuid REFERENCES kaizen_companies(id) ON DELETE SET NULL,
  client_name   text,
  client_address text,
  client_tax_id text,
  client_contact text,
  client_phone  text,
  client_email  text,
  -- Document body
  issue_date    date NOT NULL DEFAULT (now() AT TIME ZONE 'utc')::date,
  due_date      date,
  line_items    jsonb NOT NULL DEFAULT '[]'::jsonb,  -- [{description, qty, unit_price}]
  currency      text NOT NULL DEFAULT 'THB',
  non_vat_amount numeric NOT NULL DEFAULT 0,
  subtotal      numeric NOT NULL DEFAULT 0,          -- vatable amount (excl VAT)
  vat_rate      numeric NOT NULL DEFAULT 7,
  vat_amount    numeric NOT NULL DEFAULT 0,
  total         numeric NOT NULL DEFAULT 0,          -- grand total (incl VAT)
  notes         text,
  status        text NOT NULL DEFAULT 'draft',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_generated_forms_type    ON kaizen_generated_forms(form_type);
CREATE INDEX IF NOT EXISTS idx_generated_forms_company ON kaizen_generated_forms(company_id);
CREATE INDEX IF NOT EXISTS idx_generated_forms_created ON kaizen_generated_forms(created_at DESC);

ALTER TABLE kaizen_generated_forms ENABLE ROW LEVEL SECURITY;
-- No policies: only the service-role edge function may read/write.
